operator:
  # renovate: datasource=docker depName=scylladb packageName=docker.io/scylladb/scylla versioning=semver
  scyllaDBVersion: "2026.2.1"
  scyllaDBUtilsImage: "docker.io/scylladb/scylla:2026.1.0@sha256:d450d2d8636ab7b511b68180b4c535bf2294d0d6427adf11fc7f4bddfdbff35a"
  # FIXME: switch to scylladb-node-exporter image once https://scylladb.atlassian.net/browse/RELENG-711 is completed.
  scyllaDBNodeExporterImage: "quay.io/prometheus/node-exporter:v1.11.1"
  # renovate: datasource=docker depName=scylla-manager packageName=docker.io/scylladb/scylla-manager versioning=semver
  scyllaDBManagerVersion: "3.11.2@sha256:76828e1cef8d335ba78b0cb6367f09d0587f23f6531b1f6a96a31e0543ee5e58"
  # renovate: datasource=docker depName=scylla-manager-agent packageName=docker.io/scylladb/scylla-manager-agent versioning=semver
  scyllaDBManagerAgentVersion: "3.11.2@sha256:9747c7c2ba396e33fa3d97c9ef8f0738b603b2d97834c407828188b3b0f89c3b"
  bashToolsImage: "registry.access.redhat.com/ubi9/ubi:9.5-1745854298@sha256:f4ebd46d3ba96feb016d798009e1cc2404c3a4ebdac8b2479a2ac053e59f41b4"
  grafanaImage: "docker.io/grafana/grafana:12.4.5" # Generated from scylla-monitoring/versions.sh GRAFANA_VERSION.
  grafanaDefaultPlatformDashboard: "scylladb-2026.2/scylla-overview.2026.2.json"
  prometheusVersion: "v3.12.0" # Generated from scylla-monitoring/versions.sh PROMETHEUS_VERSION.
operatorTests:
  scyllaDBVersions:
    updateFrom: "2026.2.0" # One patch lower than .operator.scyllaDBVersion (if no patches yet for this minor, use a release candidate)
    upgradeFrom: "2026.1.8" # One minor lower than .operator.scyllaDBVersion
  nodeSetupImage: "quay.io/scylladb/scylla-operator-images:node-setup-v0.0.4@sha256:8d77b91db6cffb40337e3db9c9a2f73f190eda9f9e547a752f0beab8aea322ef"
  # renovate: datasource=custom.envtest depName=envtest versioning=semver
  envTestKubernetesVersion: "v1.36.2"
thirdParty:
  certManager:
    # renovate: datasource=github-releases depName=cert-manager packageName=cert-manager/cert-manager versioning=semver
    version: "1.21.0"
  prometheusOperator:
    # renovate: datasource=github-releases depName=prometheus-operator packageName=prometheus-operator/prometheus-operator versioning=semver
    version: "0.92.1" # Latest compatible with .operator.prometheusVersion (https://prometheus-operator.dev/docs/getting-started/compatibility/)
    namespace: "prometheus-operator"
