{
 "title": "Filter-Advanced",
 "tags": [ "2024.1" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "by",
    "label": "by",
    "query": "Instance : instance,Cluster : cluster,DC : dc,Shard : instance\\,shard"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(scylla_reactor_utilization, cluster)"
   },
   {
    "name": "dc",
    "label": "dc",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster\"}, dc)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(scylla_reactor_utilization{cluster=\"$cluster\", dc=~\"$dc\"}, instance)"
   },
   {
    "name": "shard",
    "label": "shard",
    "query": "label_values(scylla_reactor_utilization,shard)"
   },
   {
    "name": "classes",
    "label": "classes",
    "query": "label_values(scylla_io_queue_delay,class)"
   },
   {
    "name": "sg",
    "label": "group",
    "query": "label_values(scylla_scheduler_time_spent_on_task_quota_violations_ms,group)"
   },
   {
    "name": "iogroup",
    "label": "iogroup",
    "query": "label_values(scylla_io_queue_consumption,iogroup)"
   },
   { "name": "func", "label": "Function", "query": "sum,avg,max,min,stddev,stdvar" },
   {
    "name": "topk",
    "label": "Filter Highest",
    "query": "0, 5, 10, 20, 50, 100, 256, 500, 1000, 10000"
   },
   {
    "name": "bottomk",
    "label": "Filter Lowest",
    "query": "0, 5, 10, 20, 50, 100, 256, 500, 1000, 10000"
   },
   { "name": "scylla_version", "query": "2024.1" },
   { "name": "monitoring_version", "query": "master" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://repositories.scylladb.com/scylla/imgversion/$monitoring_version/scylla-monitoring\">"
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 4, "x": 9, "y": 0 }, "options": { "content": "# " } },
  { "type": "text", "gridPos": { "h": 1, "w": 4, "x": 13, "y": 0 }, "options": { "content": "# " } },
  { "type": "text", "gridPos": { "h": 1, "w": 7, "x": 17, "y": 0 }, "options": { "content": "# " } },
  {
   "title": "# Nodes",
   "type": "stat",
   "description": "The number of nodes configured in the cluster.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(scylla_scylladb_current_version{job=~\"$cluster|$^\", cluster=\"$cluster\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "stat",
   "description": "The number of unreachable nodes.\nUsually because a machine is down or unreachable.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(scrape_samples_scraped{job=~\"$cluster|$^\", cluster=\"$cluster\"}==0) OR vector(0))",
     "legendFormat": "Offline "
    }
   ]
  },
  {
   "title": "Inactive",
   "type": "stat",
   "description": "The number of joining and leaving nodes.\nThe number of nodes that are up but not actively part of the cluster, either because they are still joining or because they are leaving.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(scylla_node_operation_mode{cluster=\"$cluster\"}!=3)OR vector(0)",
     "legendFormat": "Offline "
    }
   ]
  },
  {
   "title": "Manager",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(max(scylla_manager_scheduler_run_indicator{type=~\"repair\",cluster=\"$cluster\"}) or on() vector(0)) + (max(scylla_manager_scheduler_run_indicator{type=~\"backup\",cluster=\"$cluster\"})*2 or on() vector(0)) + (sum(scylla_manager_server_current_version{}) or on() vector(-1))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 1, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(avg(scylla_manager_repair_progress{cluster=\"$cluster\", job=\"scylla_manager\"}) * max(scylla_manager_scheduler_run_indicator{type=\"repair\",cluster=\"$cluster\"})) or on ()  (100*avg(manager:backup_progress{cluster=\"$cluster\"}) * max(scylla_manager_scheduler_run_indicator{type=\"backup\",cluster=\"$cluster\"})) or on () vector(0)"
    }
   ]
  },
  {
   "title": "Avg Write",
   "type": "stat",
   "description": "Average Write Latency",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(wlatencya{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0)"
    }
   ]
  },
  {
   "title": "99% Write",
   "type": "stat",
   "description": "99% write Latency",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "wlatencyp99{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}}"
    }
   ]
  },
  {
   "title": "Avg Read",
   "type": "stat",
   "description": "Average Read Latency",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rlatencya{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0)"
    }
   ]
  },
  {
   "title": "99% Read",
   "type": "stat",
   "description": "99% read Latency",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rlatencyp99{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}}"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_transport_requests_served{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) + (sum(rate(scylla_thrift_served{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "description": "The percentage of the time during which Scylla utilized the CPU. Note that because Scylla does busy polling for some time before going idle, CPU utilization as seen by the operating system may be much higher. Your system is not yet CPU-bottlenecked until this metric is high.",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"} )"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "stat",
   "description": "The rate of timeouts (read and write).\n\nTimeouts are an indication of an overloaded system",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(scylla_storage_proxy_coordinator_write_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m])) or on() vector(0)) + (sum(rate(scylla_storage_proxy_coordinator_read_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[1m])) or on() vector(0))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">IO Queue Information</h1>"
  },
  {
   "title": "I/O Group consumption by instance",
   "type": "timeseries",
   "description": "This graph shows how IO queue consumption is distributed between io-groups and streams.\n\nscylla_io_queue_consumption",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_io_queue_consumption{iogroup=~\"$iogroup\", class=~\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\"}[1m])) by (instance, iogroup, stream)",
     "legendFormat": "Group {{iogroup}} {{stream}} {{dc}} {{instance}} "
    }
   ]
  },
  {
   "title": "I/O Group Queue flow ratio",
   "type": "timeseries",
   "description": "This graph shows the ratio of dispatch rate to completion rate. It is expected to be 1.0, growing larger on reactor stalls or disk problems.\n\nscylla_io_queue_flow_ratio",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk([[topk]], scylla_io_queue_flow_ratio{iogroup=~\"$iogroup\", instance=~\"[[node]]\", cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) or on ([[by]]) bottomk([[bottomk]], scylla_io_queue_flow_ratio{iogroup=~\"$iogroup\", instance=~\"[[node]]\", cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"})",
     "legendFormat": "Group {{iogroup}} {{dc}} {{instance}} {{shard}}"
    }
   ]
  },
  { "title": "$classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "classes" },
  {
   "title": "$classes I/O Queue delay by [[by]]",
   "type": "timeseries",
   "description": "Total time spent in the queue",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk([[topk]], max(rate(scylla_io_queue_total_delay_sec{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])/rate(scylla_io_queue_total_operations{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]) or on() max(scylla_io_queue_delay{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], max(rate(scylla_io_queue_total_delay_sec{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])/rate(scylla_io_queue_total_operations{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]) or on() max(scylla_io_queue_delay{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$classes Queue length by [[by]]",
   "type": "timeseries",
   "description": "Number of requests in the queue",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk([[topk]], max(scylla_io_queue_queue_length{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], max(scylla_io_queue_queue_length{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$classes I/O Queue bandwidth by [[by]]",
   "type": "timeseries",
   "description": "The queue bandwidth rate in bytes \n\nscylla_io_queue_total_bytes",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk([[topk]], sum(rate(scylla_io_queue_total_bytes{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], sum(rate(scylla_io_queue_total_bytes{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "$classes I/O Queue IOPS by [[by]]",
   "type": "timeseries",
   "description": "The rate of io queue operation\n\nsscylla_io_queue_total_operations",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk([[topk]], sum(rate(scylla_io_queue_total_operations{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], sum(rate(scylla_io_queue_total_operations{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Disk $classes I/O Queue delay by [[by]]",
   "type": "timeseries",
   "description": "Total time spent in disk",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk([[topk]], max(rate(scylla_io_queue_total_exec_sec{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])/rate(scylla_io_queue_total_operations{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]) or on() max(scylla_io_queue_delay{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], max(rate(scylla_io_queue_total_exec_sec{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])/rate(scylla_io_queue_total_operations{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]) or on() max(scylla_io_queue_delay{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]]))"
    }
   ]
  },
  {
   "title": "DISK $classes Queue length by [[by]]",
   "type": "timeseries",
   "description": "Number of requests in the disk",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk([[topk]], max(scylla_io_queue_disk_queue_length{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], max(scylla_io_queue_disk_queue_length{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "DISK $classes starvation time by [[by]]",
   "type": "timeseries",
   "description": "The time the class waited for being dispatched with non-empty software queue.\n\nLarge IO delays coupled with small starvation time denotes that scheduler is doing its job properly, and it's upper layer that overflows disk capacity.\n\nLarge IO delays coupled with large starvation time denotes that there might be some problem on the scheduler level that it cannot deliver IO requests from that class into disk in timely manner or the disk is slow and cannot afford timely dispatching.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk([[topk]], sum(rate(scylla_io_queue_starvation_time_sec{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], sum(rate(scylla_io_queue_starvation_time_sec{class=\"$classes\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Information by Task Group</h1>"
  },
  { "title": "$sg", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "sg" },
  {
   "title": "Time used by [[by]] - $sg",
   "type": "timeseries",
   "description": "Scylla employs an event-loop like reactor that alternates between the execution of different groups of tasks periodically. This graph shows how much time was spent in $sg group",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk([[topk]], $func(rate(scylla_scheduler_runtime_ms{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\",group=~\"$sg\", shard=~\"[[shard]]\"}[1m])/1000) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], $func(rate(scylla_scheduler_runtime_ms{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\",group=~\"$sg\", shard=~\"[[shard]]\"}[1m])/1000) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Time spent in task quota violations by [[by]] - $sg",
   "type": "timeseries",
   "description": "Scylla employs an event-loop like reactor that alternates between the execution of different groups of tasks periodically. The maximum amount of time during which a task group can run is called the \"task quota\". Some task groups may disrespect that and run for longer. This may cause latency issues",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk([[topk]], $func(rate(scylla_scheduler_time_spent_on_task_quota_violations_ms{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\",group=~\"$sg\", shard=~\"[[shard]]\"}[1m])/1000) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], $func(rate(scylla_scheduler_time_spent_on_task_quota_violations_ms{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\",group=~\"$sg\", shard=~\"[[shard]]\"}[1m])/1000) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Starvation time by [[by]] - $sg",
   "type": "timeseries",
   "description": "Scylla employs an event-loop like reactor that alternates between the execution of different groups of tasks periodically. The maximum amount of time during which a task group can run is called the \"task quota\". Some task groups may disrespect that and run for longer.\n\n This graph shows the amount of time the group was waiting to get CPU time.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk([[topk]], $func(rate(scylla_scheduler_starvetime_ms{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\",group=~\"$sg\", shard=~\"[[shard]]\"}[1m])/1000) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], $func(rate(scylla_scheduler_starvetime_ms{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\",group=~\"$sg\", shard=~\"[[shard]]\"}[1m])/1000) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Scheduler shares [[by]] - $sg",
   "type": "timeseries",
   "description": "Shares assigned to the $sg. Shares determine how Scylla reactor distributes the task quotas between groups (Higher share gets more quotas)",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk([[topk]], $func(scylla_scheduler_shares{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\",group=~\"$sg\", shard=~\"[[shard]]\"}) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], $func(scylla_scheduler_shares{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\",group=~\"$sg\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  { "title": "Internal node errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Internal node Errors - $cluster</h1>"
  },
  {
   "title": "Local Reads Error by [[by]]",
   "type": "timeseries",
   "description": "Number of Read requests that failed due to an 'unavailable' error",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "si:reads/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(rate(scylla_storage_proxy_coordinator_read_errors_local_node{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(rate(scylla_storage_proxy_coordinator_read_errors_local_node{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Local Write Error by [[by]]",
   "type": "timeseries",
   "description": "Number of write requests that failed due to an 'unavailable' error",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "si:writes/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(rate(scylla_storage_proxy_coordinator_write_errors_local_node{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(rate(scylla_storage_proxy_coordinator_write_errors_local_node{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 }, "content": "##  " },
  {
   "title": "Reads Unavailable Error by [[by]]",
   "type": "timeseries",
   "description": "Number of Read requests that failed due to an 'unavailable' error",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "si:reads/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(rate(scylla_storage_proxy_coordinator_read_unavailable{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(rate(scylla_storage_proxy_coordinator_read_unavailable{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Write Unavailable Error by [[by]]",
   "type": "timeseries",
   "description": "Number of write requests that failed on a local Node",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "si:writes/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(rate(scylla_storage_proxy_coordinator_write_unavailable{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(rate(scylla_storage_proxy_coordinator_write_unavailable{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Range Unavailable Error by [[by]]",
   "type": "timeseries",
   "description": "Number of write requests that failed on a local Node",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(rate(scylla_storage_proxy_coordinator_range_unavailable{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(rate(scylla_storage_proxy_coordinator_range_unavailable{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "AIO Error by [[by]]",
   "type": "timeseries",
   "description": "Number of AIO Errors",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(rate(scylla_reactor_aio_errors{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(rate(scylla_reactor_aio_errors{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Ignored Future By [[by]]",
   "type": "timeseries",
   "description": "Total number of abandoned failed futures, futures destroyed while still containing an exception.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], sum(rate(scylla_reactor_abandoned_failed_futures{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], sum(rate(scylla_reactor_abandoned_failed_futures{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "C++ Exceptions [[by]]",
   "type": "timeseries",
   "description": "Number of C++ exceptions thrown.\n\n An exception by itself does not indicate a problem",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], sum(rate(scylla_reactor_cpp_exceptions{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], sum(rate(scylla_reactor_cpp_exceptions{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  { "title": "Commit Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 59 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Commit log Information</h1>"
  },
  {
   "title": "Avg reserved disk space by [[by]]",
   "type": "timeseries",
   "description": "Holds the size of disk space in bytes reserved for data so far. A too high value indicates that we have some bottleneck in the writing to sstables path",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(scylla_commitlog_disk_total_bytes{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(scylla_commitlog_disk_total_bytes{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Avg used disk space by [[by]]",
   "type": "timeseries",
   "description": "Holds the size of disk space in bytes used for data so far. A too high value indicates that we have some bottleneck in the writing to sstables path",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(scylla_commitlog_disk_active_bytes{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(scylla_commitlog_disk_active_bytes{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Avg flush by [[by]]",
   "type": "timeseries",
   "description": "Counts a number of times the flush() method was called for a file",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(rate(scylla_commitlog_flush{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(rate(scylla_commitlog_flush{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Segments by [[by]]",
   "type": "timeseries",
   "description": "Holds the current number of segments",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(scylla_commitlog_segments{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(scylla_commitlog_segments{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Avg flush limit exceeded by [[by]]",
   "type": "timeseries",
   "description": "Counts a number of times a flush limit was exceeded. A non-zero value indicates that there are too many pending flush operations (see pending_flushes) and some of them will be blocked till the total amount of pending flush operations drops below 5.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(rate(scylla_commitlog_flush_limit_exceeded{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(rate(scylla_commitlog_flush_limit_exceeded{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Pending allocations by [[by]]",
   "type": "timeseries",
   "description": "Holds the number of currently pending allocations. A non-zero value indicates that we have a bottleneck in the disk write flow.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(scylla_commitlog_pending_allocations{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(scylla_commitlog_pending_allocations{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Pending flush by [[by]]",
   "type": "timeseries",
   "description": "Counts a number of requests blocked due to memory pressure. A non-zero value indicates that the commitlog memory quota is not enough to serve the required amount of requests.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(scylla_commitlog_pending_flushes{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(scylla_commitlog_pending_flushes{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Unused segments by [[by]]",
   "type": "timeseries",
   "description": "Holds the current number of unused segments. A non-zero value indicates that the disk write path became temporary slow.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(scylla_commitlog_unused_segments{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(scylla_commitlog_unused_segments{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  {
   "title": "Allocating segments by [[by]]",
   "type": "timeseries",
   "description": "Holds the number of not closed segments that still have some free space. This value should not get too high.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "topk([[topk]], avg(scylla_commitlog_allocating_segments{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])) or on ([[by]]) bottomk([[bottomk]], avg(scylla_commitlog_allocating_segments{instance=~\"[[node]]\" ,cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]]))"
    }
   ]
  },
  { "title": "Your panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 80 },
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Your Panels</h1>"
   }
  },
  {
   "title": "Your Graph here",
   "type": "timeseries",
   "description": "This graph panel was left empty on purpose for ad-hoc usage. Change it when needed. Pay attention that changes to the panel will not be saved.\n\nIf you do need a panel that can be saved, create a new dashboard, or edit the panel inside the json file",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } }
  },
  {
   "title": "Your Graph here",
   "type": "timeseries",
   "description": "This graph panel was left empty on purpose for ad-hoc usage. Change it when needed. Pay attention that changes to the panel will not be saved.\n\nIf you do need a panel that can be saved, create a new dashboard, or edit the panel inside the json file",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 88 },
   "options": {
    "content": "<div style=\"color:#5780C1; border-bottom: 0px solid #5780C1;\">Scylla Monitoring version - master</div> <div style=\"\"><a href=\"https://github.com/scylladb/scylla-monitoring/issues/new?body=scylla-version%3D[[scylla_version]]%0Amonitoring-version%3D[[monitoring_version]]%0Adashboard%3D${__dashboard.uid}\" target=\"_blank\">\n<input title=\"Report an issue with Scylla Monitoring\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;Report an issue on this page&nbsp;\"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"/render/d/${__dashboard.uid}?orgId=1&from=${__from}&to=${__to}&width=1600&height=-1\" target=\"_blank\" download=\"dashboard_${__dashboard.uid}-${__from:date:iso}.png\"><input title=\"Make a Screenshot\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;&nbsp;&nbsp;Screenshot&nbsp;&nbsp;&nbsp;\"></input></a></span></div>"
   }
  }
 ]
}