{
 "title": "Scylla Overview Metrics 2.2",
 "tags": [ "2.2" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "by", "label": "by", "query": "Instance,Shard,Cluster" },
   { "name": "node", "label": "node", "query": "scylla_reactor_utilization" },
   {
    "name": "shard",
    "label": "shard",
    "query": "scylla_reactor_utilization{instance=~\"$node\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "content": "<img src=\"http://www.scylladb.com/wp-content/uploads/logo-scylla-white-simple.png\" height=\"70\">\n<hr style=\"border-top: 3px solid #5780c1;\">"
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"scylla\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(scrape_samples_scraped{job=\"scylla\"}==0) OR vector(0)",
     "legendFormat": "Unreachable"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 6, "x": 4, "y": 6 }, "content": "##  " },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job!=\"scylla_manager\"",
     "legendFormat": "{{description}}",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 } },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{} ) by ([[by]])",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Requests Served",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_transport_requests_served{}[30s])) by ([[by]]) + sum(irate(scylla_thrift_served{}[30s])) by ([[by]])",
     "legendFormat": "Requests Served"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_avail{mountpoint=\"/var/lib/scylla\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "(sum(node_filesystem_size{mountpoint=\"/var/lib/scylla\"})-sum(node_filesystem_avail{mountpoint=\"/var/lib/scylla\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Average write latency by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_latency_sum{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])/sum(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "95th percentile write latency by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "99th percentile write latency by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "Average read latency by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_read_latency_sum{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])/sum(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "95th percentile read latency by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "99th percentile read latency by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]], le))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Reads and Writes</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 30 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Timeouts and Errors</h1>"
  },
  {
   "title": "Foreground Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_foreground_writes{}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Foreground Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_foreground_reads{}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Write Timeouts per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_storage_proxy_coordinator_write_timeouts{}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Write Unavailable per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_storage_proxy_coordinator_write_unavailable{}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Background Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_background_writes{}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Background Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_background_reads{}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Read Timeouts per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_storage_proxy_coordinator_read_timeouts{}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Read Unavailable per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 42 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_storage_proxy_coordinator_read_unavailable{}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cache</h1>"
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_row_hits{}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_row_misses{}[30s])) by ([[by]])"
    }
   ]
  }
 ]
}