{
 "title": "Scylla Per Server Metrics 2.2",
 "tags": [ "2.2" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "monitor_disk", "query": "node_disk_bytes_read" },
   { "name": "monitor_network_interface", "query": "node_network_receive_packets" },
   { "name": "by", "label": "by", "query": "Instance,Shard,Cluster" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(scylla_reactor_utilization, instance)"
   },
   {
    "name": "shard",
    "label": "shard",
    "query": "scylla_reactor_utilization{instance=~\"$node\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "content": "<img src=\"http://www.scylladb.com/wp-content/uploads/logo-scylla-white-simple.png\" height=\"70\">\n<hr style=\"border-top: 3px solid #5780c1;\">"
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"scylla\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(scrape_samples_scraped{job=\"scylla\"}==0) OR vector(0)",
     "legendFormat": "Unreachable"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 6, "x": 4, "y": 6 }, "content": "##  " },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_transport_requests_served{}[30s])) + sum(irate(scylla_thrift_served{}[30s]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 } },
  {
   "title": "Load per [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{instance=~\"[[node]]\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Requests Served per [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_transport_requests_served{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]]) + sum(irate(scylla_thrift_served{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_avail{mountpoint=\"/var/lib/scylla\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "(sum(node_filesystem_size{mountpoint=\"/var/lib/scylla\"})-sum(node_filesystem_avail{mountpoint=\"/var/lib/scylla\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 18 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Reads and Writes</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Timeouts and Errors</h1>"
  },
  {
   "title": "Foreground Writes per [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_foreground_writes{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Foreground Reads per [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_foreground_reads{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Write Timeouts per Second per [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_storage_proxy_coordinator_write_timeouts{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Write Unavailable per Second per [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_storage_proxy_coordinator_write_unavailable{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Background Writes per [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_background_writes{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Background Reads per [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_background_reads{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Read Timeouts per Second per [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_storage_proxy_coordinator_read_timeouts{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Read Unavailable per Second per [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_storage_proxy_coordinator_read_unavailable{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Replica</h1>"
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_database_total_reads{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_database_total_writes{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Active sstable reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_database_active_reads{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Queued sstable reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_database_queued_reads{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Writes currently blocked on dirty",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_database_requests_blocked_memory_current{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Writes currently blocked on commitlog",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_commitlog_pending_allocations{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 } },
  {
   "title": "Reads failed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_database_total_reads_failed{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Writes blocked on dirty",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_database_requests_blocked_memory{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Writes blocked on commitlog",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_commitlog_requests_blocked_memory{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 55 } },
  { "type": "text", "gridPos": { "h": 6, "w": 6, "x": 6, "y": 55 } },
  {
   "title": "Writes failed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_database_total_writes_failed{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Writes timed out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_database_total_writes_timedout{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Disk $monitor_disk</h1>"
  },
  {
   "title": "Disk Writes per Server per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed{device=\"$monitor_disk\"}[30s])"
    }
   ]
  },
  {
   "title": "Disk Reads per Server per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 67 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed{device=\"$monitor_disk\"}[30s])"
    }
   ]
  },
  {
   "title": "Disk Writes Bps per Server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_bytes_written{device=\"$monitor_disk\"}[30s])"
    }
   ]
  },
  {
   "title": "Disk Read Bps per Server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_bytes_read{device=\"$monitor_disk\"}[30s])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cache</h1>"
  },
  {
   "title": "Reads with no misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_reads{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s]) - irate(scylla_cache_reads_with_misses{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Reads with misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_reads_with_misses{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Row Hits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_row_hits{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Partition Hits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 85 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_partition_hits{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Row Misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_row_misses{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Partition Misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 85 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_partition_misses{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Row Insertions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_row_insertions{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Partition Insertions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 91 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_partition_insertions{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Row Evictions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_row_evictions{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Partition Evictions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 91 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_partition_evictions{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Row Merges",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_rows_merged_from_memtable{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Partition Merges",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 97 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_partition_merges{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Row Removals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_row_removals{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Partition Removals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 97 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_partition_removals{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_cache_rows{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_cache_partitions{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Used Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_cache_bytes_used{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_cache_bytes_total{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 109 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Memory</h1>"
  },
  {
   "title": "LSA total memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_lsa_total_space_bytes{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Non-LSA used memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_lsa_non_lsa_used_space_bytes{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 121 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Network $monitor_network_interface</h1>"
  },
  {
   "title": "Interface Rx Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets{device=\"$monitor_network_interface\"}[30s])"
    }
   ]
  },
  {
   "title": "Interface Tx Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets{device=\"$monitor_network_interface\"}[30s])"
    }
   ]
  },
  {
   "title": "Interface Rx Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{device=\"$monitor_network_interface\"}[30s])"
    }
   ]
  },
  {
   "title": "Interface Tx Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes{device=\"$monitor_network_interface\"}[30s])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 139 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Compaction</h1>"
  },
  {
   "title": "Running Compactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_compaction_manager_compactions{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 151 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">CQL</h1>"
  },
  {
   "title": "CQL Insert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 157 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_inserts{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[300s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "CQL Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 157 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_reads{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[300s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "CQL Deletes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 157 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_deletes{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[300s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "CQL Updates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 157 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_updates{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[300s])) by ([[by]])"
    }
   ]
  }
 ]
}