// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/scylladb/scylla-operator/pkg/multiregionclient/scylla/clientset/versioned/typed/scylla/v2alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeScyllaV2alpha1 struct {
	*testing.Fake
}

func (c *FakeScyllaV2alpha1) ScyllaClusters(namespace string) v2alpha1.ScyllaClusterInterface {
	return &FakeScyllaClusters{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeScyllaV2alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
