apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla
spec:
  agentVersion: 3.9.0@sha256:fefeb01e83a5304b9693a9e04f0a51a0101b80ccb2402038991923738262e39d
  version: 2026.1.0
  developerMode: true
  automaticOrphanedNodeCleanup: true
  datacenter:
    name: us-east-1
    racks:
      - name: us-east-1a
        members: 1
        storage:
          capacity: 1Gi
          storageClassName: scylladb-local-xfs
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1Gi
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: scylla.scylladb.com/node-type
                      operator: In
                      values:
                        - scylla
          tolerations:
            - effect: NoSchedule
              key: scylla-operator.scylladb.com/dedicated
              operator: Equal
              value: scyllaclusters
