// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiscyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	versioned "github.com/scylladb/scylla-operator/pkg/client/scylla/clientset/versioned"
	internalinterfaces "github.com/scylladb/scylla-operator/pkg/client/scylla/informers/externalversions/internalinterfaces"
	scyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/client/scylla/listers/scylla/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScyllaOperatorConfigInformer provides access to a shared informer and lister for
// ScyllaOperatorConfigs.
type ScyllaOperatorConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() scyllav1alpha1.ScyllaOperatorConfigLister
}

type scyllaOperatorConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewScyllaOperatorConfigInformer constructs a new informer for ScyllaOperatorConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScyllaOperatorConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScyllaOperatorConfigInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredScyllaOperatorConfigInformer constructs a new informer for ScyllaOperatorConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScyllaOperatorConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ScyllaV1alpha1().ScyllaOperatorConfigs().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ScyllaV1alpha1().ScyllaOperatorConfigs().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ScyllaV1alpha1().ScyllaOperatorConfigs().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ScyllaV1alpha1().ScyllaOperatorConfigs().Watch(ctx, options)
			},
		}, client),
		&apiscyllav1alpha1.ScyllaOperatorConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *scyllaOperatorConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScyllaOperatorConfigInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scyllaOperatorConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiscyllav1alpha1.ScyllaOperatorConfig{}, f.defaultInformer)
}

func (f *scyllaOperatorConfigInformer) Lister() scyllav1alpha1.ScyllaOperatorConfigLister {
	return scyllav1alpha1.NewScyllaOperatorConfigLister(f.Informer().GetIndexer())
}
