// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiscyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	versioned "github.com/scylladb/scylla-operator/pkg/client/scylla/clientset/versioned"
	internalinterfaces "github.com/scylladb/scylla-operator/pkg/client/scylla/informers/externalversions/internalinterfaces"
	scyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/client/scylla/listers/scylla/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScyllaDBDatacenterStatusReportInformer provides access to a shared informer and lister for
// ScyllaDBDatacenterStatusReports.
type ScyllaDBDatacenterStatusReportInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() scyllav1alpha1.ScyllaDBDatacenterStatusReportLister
}

type scyllaDBDatacenterStatusReportInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScyllaDBDatacenterStatusReportInformer constructs a new informer for ScyllaDBDatacenterStatusReport type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScyllaDBDatacenterStatusReportInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScyllaDBDatacenterStatusReportInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScyllaDBDatacenterStatusReportInformer constructs a new informer for ScyllaDBDatacenterStatusReport type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScyllaDBDatacenterStatusReportInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ScyllaV1alpha1().ScyllaDBDatacenterStatusReports(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ScyllaV1alpha1().ScyllaDBDatacenterStatusReports(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ScyllaV1alpha1().ScyllaDBDatacenterStatusReports(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ScyllaV1alpha1().ScyllaDBDatacenterStatusReports(namespace).Watch(ctx, options)
			},
		},
		&apiscyllav1alpha1.ScyllaDBDatacenterStatusReport{},
		resyncPeriod,
		indexers,
	)
}

func (f *scyllaDBDatacenterStatusReportInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScyllaDBDatacenterStatusReportInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scyllaDBDatacenterStatusReportInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiscyllav1alpha1.ScyllaDBDatacenterStatusReport{}, f.defaultInformer)
}

func (f *scyllaDBDatacenterStatusReportInformer) Lister() scyllav1alpha1.ScyllaDBDatacenterStatusReportLister {
	return scyllav1alpha1.NewScyllaDBDatacenterStatusReportLister(f.Informer().GetIndexer())
}
