{
 "title": "Scylla Per-Server Disk I/O 2.2",
 "tags": [ "2.2" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "monitor_disk", "query": "node_disk_bytes_read" },
   { "name": "by", "label": "by", "query": "Instance,Shard,Cluster" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(scylla_reactor_utilization, instance)"
   },
   {
    "name": "shard",
    "label": "shard",
    "query": "scylla_reactor_utilization{instance=~\"$node\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 },
   "content": "<img src=\"http://www.scylladb.com/wp-content/uploads/logo-scylla-white-simple.png\" height=\"70\">\n<hr style=\"border-top: 3px solid #5780c1;\">"
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"scylla\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(scrape_samples_scraped{job=\"scylla\"}==0) OR vector(0)",
     "legendFormat": "Unreachable"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 6, "x": 4, "y": 0 }, "content": "##  " },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_transport_requests_served{}[30s])) + sum(irate(scylla_thrift_served{}[30s]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Load per [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{instance=~\"[[node]]\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Requests Served per [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_transport_requests_served{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]]) + sum(irate(scylla_thrift_served{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_avail{mountpoint=\"/var/lib/scylla\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "(sum(node_filesystem_size{mountpoint=\"/var/lib/scylla\"})-sum(node_filesystem_avail{mountpoint=\"/var/lib/scylla\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Disk Activity</h1>"
  },
  {
   "title": "Disk Writes per Server per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed{device=\"$monitor_disk\"}[30s])"
    }
   ]
  },
  {
   "title": "Disk Reads per Server per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed{device=\"$monitor_disk\"}[30s])"
    }
   ]
  },
  {
   "title": "Disk Writes Bps per Server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_bytes_written{device=\"$monitor_disk\"}[30s])"
    }
   ]
  },
  {
   "title": "Disk Read Bps per Server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_bytes_read{device=\"$monitor_disk\"}[30s])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">I/O Queue</h1>"
  },
  {
   "title": "Compactions I/O Queue delay by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_compaction_delay{instance=~\"[[node]]\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Compactions I/O Queue bandwidth by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_compaction_total_bytes{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Compactions I/O Queue IOPS by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_compaction_total_operations{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query I/O Queue delay by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_query_delay{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query I/O Queue bandwidth by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_query_total_bytes{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Query I/O Queue IOPS by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_query_total_operations{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue delay by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_commitlog_delay{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue bandwidth by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_commitlog_total_bytes{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue IOPS by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_commitlog_total_operations{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue delay by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_memtable_flush_delay{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue bandwidth by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_memtable_flush_total_bytes{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue IOPS by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_memtable_flush_total_operations{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue delay by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_streaming_read_delay{instance=~\"[[node]]\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue bandwidth by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_read_total_bytes{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue IOPS by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_read_total_operations{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue delay by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_streaming_write_delay{instance=~\"[[node]]\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue bandwidth by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_write_total_bytes{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue IOPS by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_write_total_operations{instance=~\"[[node]]\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  }
 ]
}