apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-manager-cluster
  namespace: scylla-manager
  annotations:
    scylla-operator.scylladb.com/disable-global-scylladb-manager-integration: "true"
spec:
  version: 2026.1.1
  agentVersion: 3.10.1@sha256:aa85a3da293d0e5ca29214a575efe79b352d6678343d2f6d9aee711ac339f903
  repository: docker.io/scylladb/scylla
  agentRepository: docker.io/scylladb/scylla-manager-agent
  developerMode: true
  cpuset: true
  datacenter:
    name: manager-dc
    racks:
    - members: 1
      name: manager-rack
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: scylla.scylladb.com/node-type
                operator: In
                values:
                - scylla
        tolerations:
        - effect: NoSchedule
          key: scylla-operator.scylladb.com/dedicated
          operator: Equal
          value: scyllaclusters
      resources:
        limits:
          cpu: 1
          memory: 200Mi
        requests:
          cpu: 1
          memory: 200Mi
      storage:
        capacity: 5Gi
        storageClassName: scylladb-local-xfs
