// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/scylladb/scylla-operator/pkg/client/scylla/clientset/versioned/typed/scylla/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeScyllaV1alpha1 struct {
	*testing.Fake
}

func (c *FakeScyllaV1alpha1) ScyllaClusterManagers(namespace string) v1alpha1.ScyllaClusterManagerInterface {
	return &FakeScyllaClusterManagers{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeScyllaV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
