// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	scyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/client/scylla/clientset/versioned/typed/scylla/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeScyllaDBDatacenterNodesStatusReports implements ScyllaDBDatacenterNodesStatusReportInterface
type fakeScyllaDBDatacenterNodesStatusReports struct {
	*gentype.FakeClientWithList[*v1alpha1.ScyllaDBDatacenterNodesStatusReport, *v1alpha1.ScyllaDBDatacenterNodesStatusReportList]
	Fake *FakeScyllaV1alpha1
}

func newFakeScyllaDBDatacenterNodesStatusReports(fake *FakeScyllaV1alpha1, namespace string) scyllav1alpha1.ScyllaDBDatacenterNodesStatusReportInterface {
	return &fakeScyllaDBDatacenterNodesStatusReports{
		gentype.NewFakeClientWithList[*v1alpha1.ScyllaDBDatacenterNodesStatusReport, *v1alpha1.ScyllaDBDatacenterNodesStatusReportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("scylladbdatacenternodesstatusreports"),
			v1alpha1.SchemeGroupVersion.WithKind("ScyllaDBDatacenterNodesStatusReport"),
			func() *v1alpha1.ScyllaDBDatacenterNodesStatusReport {
				return &v1alpha1.ScyllaDBDatacenterNodesStatusReport{}
			},
			func() *v1alpha1.ScyllaDBDatacenterNodesStatusReportList {
				return &v1alpha1.ScyllaDBDatacenterNodesStatusReportList{}
			},
			func(dst, src *v1alpha1.ScyllaDBDatacenterNodesStatusReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ScyllaDBDatacenterNodesStatusReportList) []*v1alpha1.ScyllaDBDatacenterNodesStatusReport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ScyllaDBDatacenterNodesStatusReportList, items []*v1alpha1.ScyllaDBDatacenterNodesStatusReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
