// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	scyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/client/scylla/clientset/versioned/typed/scylla/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeScyllaDBDatacenterStatusReports implements ScyllaDBDatacenterStatusReportInterface
type fakeScyllaDBDatacenterStatusReports struct {
	*gentype.FakeClientWithList[*v1alpha1.ScyllaDBDatacenterStatusReport, *v1alpha1.ScyllaDBDatacenterStatusReportList]
	Fake *FakeScyllaV1alpha1
}

func newFakeScyllaDBDatacenterStatusReports(fake *FakeScyllaV1alpha1, namespace string) scyllav1alpha1.ScyllaDBDatacenterStatusReportInterface {
	return &fakeScyllaDBDatacenterStatusReports{
		gentype.NewFakeClientWithList[*v1alpha1.ScyllaDBDatacenterStatusReport, *v1alpha1.ScyllaDBDatacenterStatusReportList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("scylladbdatacenterstatusreports"),
			v1alpha1.SchemeGroupVersion.WithKind("ScyllaDBDatacenterStatusReport"),
			func() *v1alpha1.ScyllaDBDatacenterStatusReport { return &v1alpha1.ScyllaDBDatacenterStatusReport{} },
			func() *v1alpha1.ScyllaDBDatacenterStatusReportList {
				return &v1alpha1.ScyllaDBDatacenterStatusReportList{}
			},
			func(dst, src *v1alpha1.ScyllaDBDatacenterStatusReportList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ScyllaDBDatacenterStatusReportList) []*v1alpha1.ScyllaDBDatacenterStatusReport {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ScyllaDBDatacenterStatusReportList, items []*v1alpha1.ScyllaDBDatacenterStatusReport) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
