// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeScyllaDBMonitorings implements ScyllaDBMonitoringInterface
type FakeScyllaDBMonitorings struct {
	Fake *FakeScyllaV1alpha1
	ns   string
}

var scylladbmonitoringsResource = schema.GroupVersionResource{Group: "scylla.scylladb.com", Version: "v1alpha1", Resource: "scylladbmonitorings"}

var scylladbmonitoringsKind = schema.GroupVersionKind{Group: "scylla.scylladb.com", Version: "v1alpha1", Kind: "ScyllaDBMonitoring"}

// Get takes name of the scyllaDBMonitoring, and returns the corresponding scyllaDBMonitoring object, and an error if there is any.
func (c *FakeScyllaDBMonitorings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ScyllaDBMonitoring, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(scylladbmonitoringsResource, c.ns, name), &v1alpha1.ScyllaDBMonitoring{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScyllaDBMonitoring), err
}

// List takes label and field selectors, and returns the list of ScyllaDBMonitorings that match those selectors.
func (c *FakeScyllaDBMonitorings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ScyllaDBMonitoringList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(scylladbmonitoringsResource, scylladbmonitoringsKind, c.ns, opts), &v1alpha1.ScyllaDBMonitoringList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ScyllaDBMonitoringList{ListMeta: obj.(*v1alpha1.ScyllaDBMonitoringList).ListMeta}
	for _, item := range obj.(*v1alpha1.ScyllaDBMonitoringList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested scyllaDBMonitorings.
func (c *FakeScyllaDBMonitorings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(scylladbmonitoringsResource, c.ns, opts))

}

// Create takes the representation of a scyllaDBMonitoring and creates it.  Returns the server's representation of the scyllaDBMonitoring, and an error, if there is any.
func (c *FakeScyllaDBMonitorings) Create(ctx context.Context, scyllaDBMonitoring *v1alpha1.ScyllaDBMonitoring, opts v1.CreateOptions) (result *v1alpha1.ScyllaDBMonitoring, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(scylladbmonitoringsResource, c.ns, scyllaDBMonitoring), &v1alpha1.ScyllaDBMonitoring{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScyllaDBMonitoring), err
}

// Update takes the representation of a scyllaDBMonitoring and updates it. Returns the server's representation of the scyllaDBMonitoring, and an error, if there is any.
func (c *FakeScyllaDBMonitorings) Update(ctx context.Context, scyllaDBMonitoring *v1alpha1.ScyllaDBMonitoring, opts v1.UpdateOptions) (result *v1alpha1.ScyllaDBMonitoring, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(scylladbmonitoringsResource, c.ns, scyllaDBMonitoring), &v1alpha1.ScyllaDBMonitoring{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScyllaDBMonitoring), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeScyllaDBMonitorings) UpdateStatus(ctx context.Context, scyllaDBMonitoring *v1alpha1.ScyllaDBMonitoring, opts v1.UpdateOptions) (*v1alpha1.ScyllaDBMonitoring, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(scylladbmonitoringsResource, "status", c.ns, scyllaDBMonitoring), &v1alpha1.ScyllaDBMonitoring{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScyllaDBMonitoring), err
}

// Delete takes name of the scyllaDBMonitoring and deletes it. Returns an error if one occurs.
func (c *FakeScyllaDBMonitorings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(scylladbmonitoringsResource, c.ns, name, opts), &v1alpha1.ScyllaDBMonitoring{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeScyllaDBMonitorings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(scylladbmonitoringsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ScyllaDBMonitoringList{})
	return err
}

// Patch applies the patch and returns the patched scyllaDBMonitoring.
func (c *FakeScyllaDBMonitorings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ScyllaDBMonitoring, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scylladbmonitoringsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ScyllaDBMonitoring{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScyllaDBMonitoring), err
}
