# Scylla Manager image
image:
  repository: docker.io/scylladb
  tag: 3.9.0@sha256:8003fc2d6e315ce2b33863a5c6cd67bcf8d8ceca569723f68dba15cc1645c961
controllerImage:
  repository: docker.io/scylladb
logLevel: info
# Resources allocated to Scylla Manager pods
resources:
  requests:
    cpu: 10m
    memory: 20Mi
# Resources allocated to Scylla Manager Controller pods
controllerResources:
  requests:
    cpu: 10m
    memory: 20Mi
# Scylla instance for Manager
scylla:
  fullnameOverride: scylla-manager-cluster
  scyllaImage:
    repository: docker.io/scylladb/scylla
    tag: 2026.1.1
  agentImage:
    tag: 3.9.0@sha256:fefeb01e83a5304b9693a9e04f0a51a0101b80ccb2402038991923738262e39d
    repository: docker.io/scylladb/scylla-manager-agent
  developerMode: true
  cpuset: true
  datacenter: manager-dc
  racks:
    - name: manager-rack
      members: 1
      storage:
        capacity: 5Gi
        storageClassName: scylladb-local-xfs
      resources:
        limits:
          cpu: 1
          memory: 200Mi
        requests:
          cpu: 1
          memory: 200Mi
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: scylla.scylladb.com/node-type
                    operator: In
                    values:
                      - scylla
        tolerations:
          - key: scylla-operator.scylladb.com/dedicated
            operator: Equal
            value: scyllaclusters
            effect: NoSchedule
