{
 "title": "Overview",
 "tags": [ "2025.5" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(scylla_reactor_utilization, cluster)"
   },
   {
    "name": "by",
    "label": "by",
    "query": "Cluster : cluster,DC : dc, Instance : instance, Shard : instance\\,shard"
   },
   {
    "name": "dc",
    "label": "dc",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster\"}, dc)"
   },
   { "name": "mount_point", "label": "Mount path", "query": "node_filesystem_avail_bytes" },
   {
    "name": "cluster_name",
    "label": "cluster_name",
    "query": {
     "query": "label_values(scylla_scylladb_current_version,cluster_name)"
    }
   },
   {
    "name": "account_name",
    "label": "account_name",
    "query": {
     "query": "label_values(scylla_scylladb_current_version,account_name)"
    }
   },
   {
    "name": "sg",
    "query": "label_values(scylla_scheduler_runtime_ms{cluster=~\"$cluster\", group=~\"sl:.*|commitlog\"},group)"
   },
   { "name": "dash_version", "query": "2025-5" },
   {
    "name": "all_scyllas_versions",
    "query": "label_values(scylla_scylladb_current_version{cluster=\"$cluster\"}, version)"
   },
   {
    "name": "count_dc",
    "query": {
     "query": "query_result(count(up{job=~\"$cluster|$^\"}) by (dc))"
    }
   },
   { "name": "scylla_version", "query": "2025.5" },
   { "name": "monitoring_version", "query": "master" }
  ]
 },
 "panels": [
  {
   "title": "Cluster overview $cluster $account_name $cluster_name ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "The cluster status",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(max(scylla_manager_scheduler_run_indicator{type=~\"repair\",cluster=\"$cluster\"})*2 + max(scylla_manager_scheduler_run_indicator{type=~\"backup\",cluster=\"$cluster\"}))>0",
     "legendFormat": "Manager"
    },
    {
     "expr": "count(scrape_samples_scraped{job=~\"$cluster|$^\", cluster=\"$cluster\"}==0) > 0",
     "legendFormat": "Unreachable"
    },
    {
     "expr": "count(scylla_node_operation_mode{cluster=\"$cluster\"}<3)>0",
     "legendFormat": "Joining"
    },
    {
     "expr": "count(scylla_node_operation_mode{cluster=\"$cluster\"}>3)>0",
     "legendFormat": "Leaving"
    }
   ]
  },
  {
   "title": "# Nodes",
   "type": "stat",
   "description": "The number of nodes configured in the cluster.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(scylla_scylladb_current_version{job=~\"$cluster|$^\", cluster=\"$cluster\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(scylla_node_operation_mode!=3) >0",
     "legendFormat": "Inactive"
    },
    {
     "expr": "(count(scrape_samples_scraped{job=~\"$cluster|$^\", cluster=\"$cluster\"}==0) OR vector(0))>0",
     "legendFormat": "Unreachable"
    }
   ]
  },
  {
   "title": "# Cores",
   "type": "stat",
   "description": "The number of CPU Cores actively used in the cluster.\n\nNote that CPU Cores that belongs to unreachable nodes, or nodes that are not in normal mode, will not be counted",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count(scylla_reactor_utilization{job=~\"$cluster|$^\", cluster=\"$cluster\"}) by (instance) * on(instance) (scylla_node_operation_mode{job=~\"$cluster|$^\", cluster=\"$cluster\"}== bool 3))"
    }
   ]
  },
  {
   "title": "# Tables",
   "type": "stat",
   "description": "The number of tables",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(scylla_column_family_cache_hit_rate{cluster=\"$cluster\", ks!~\"system.*\"}) by(cf, ks))"
    }
   ]
  },
  {
   "title": "Writes/s",
   "type": "stat",
   "description": "Writes operations reaching the cluster",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", scheduling_group_name=~\"sl:.*\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Avg Write",
   "type": "stat",
   "description": "Average Write Latency",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(wlatencya{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0)"
    }
   ]
  },
  {
   "title": "P99 Write",
   "type": "stat",
   "description": "P99 write Latency",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(wlatencyp99{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0)"
    }
   ]
  },
  {
   "title": "Reads/s",
   "type": "stat",
   "description": "Reads operations reaching the cluster",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", scheduling_group_name=~\"sl:.*\"}[$__rate_interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Avg Read",
   "type": "stat",
   "description": "Average Read Latency",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rlatencya{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0)"
    }
   ]
  },
  {
   "title": "P99",
   "type": "stat",
   "description": "P99 read Latency",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rlatencyp99{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0)"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "description": "The percentage of the time during which Scylla utilized the CPU. Note that because Scylla does busy polling for some time before going idle, CPU utilization as seen by the operating system may be much higher. Your system is not yet CPU-bottlenecked until this metric is high.",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(rate(scylla_scheduler_runtime_ms{group=~\"sl:.*|commitlog\", instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by (group)/10)"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "stat",
   "description": "The rate of timeouts (read and write).\n\nTimeouts are an indication of an overloaded system",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(scylla_storage_proxy_coordinator_write_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) or on() vector(0)) + (sum(rate(scylla_storage_proxy_coordinator_read_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) or on() vector(0))"
    }
   ]
  },
  { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 } },
  {
   "title": "Service Level",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "avg(rate(scylla_scheduler_runtime_ms{cluster=\"$cluster\", group=~\"sl:.*\"}[$__rate_interval])) by (group)/10",
     "legendFormat": "runtime"
    },
    {
     "expr": "round(sum(label_replace(rate(scylla_storage_proxy_coordinator_read_latency_count{cluster=\"$cluster\", scheduling_group_name=~\"sl:.*\"}[$__rate_interval]), \"group\", \"$1\", \"scheduling_group_name\", \"(.*)\")) by (group))",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum(label_replace(rate(scylla_storage_proxy_coordinator_write_latency_count{cluster=\"$cluster\", scheduling_group_name=~\"sl:.*\"}[$__rate_interval]), \"group\", \"$1\", \"scheduling_group_name\", \"(.*)\")) by (group))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(scylla_scheduler_shares{cluster=\"$cluster\", group=~\"sl.*\"}) by (group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DCs Data",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "count(scylla_scylladb_current_version ) by (dc)",
     "legendFormat": "nodes"
    },
    {
     "expr": "count(scylla_reactor_utilization) by (dc)",
     "legendFormat": "cores"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"$mount_point\", cluster=\"$cluster\", dc=~\"..*\"} - node_filesystem_avail_bytes{mountpoint=\"$mount_point\",cluster=\"$cluster\", dc=~\"..*\"}) by (dc)",
     "legendFormat": "used_bytes"
    },
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_latency_count{cluster=\"$cluster\"}[$__rate_interval])) by(dc)",
     "legendFormat": "writes"
    },
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_read_latency_count{cluster=\"$cluster\"}[$__rate_interval])) by(dc)",
     "legendFormat": "reads"
    }
   ]
  },
  {
   "title": "Writes/s",
   "type": "timeseries",
   "description": "Write attempts - include all writes that reached the coordinator node, even if they will eventually fail",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "round(sum(rate(scylla_storage_proxy_coordinator_write_latency_summary_count{cluster=\"$cluster\", dc=~\"$dc\", scheduling_group_name=~\"$sg\"}[$__rate_interval])) by (scheduling_group_name))",
     "legendFormat": "{{scheduling_group_name}} Writes/s"
    }
   ]
  },
  {
   "title": "Average Write Latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "wlatencya{by=\"cluster\", cluster=\"$cluster\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}}"
    }
   ]
  },
  {
   "title": "Write Latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "wlatencyp95{by=\"cluster\", cluster=\"$cluster\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}} 95%"
    },
    {
     "expr": "wlatencyp99{by=\"cluster\", cluster=\"$cluster\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}} 99%"
    }
   ]
  },
  {
   "title": "Reads/s",
   "type": "timeseries",
   "description": "Read attempts - include all reads that reached the coordinator node, even if they will eventually fail",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "round(sum(rate(scylla_storage_proxy_coordinator_read_latency_summary_count{cluster=\"$cluster\", dc=~\"$dc\",scheduling_group_name=~\"$sg\"}[$__rate_interval])) by (scheduling_group_name))",
     "legendFormat": "{{scheduling_group_name}} Reads/s"
    }
   ]
  },
  {
   "title": "Average Read Latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rlatencya{by=\"cluster\", cluster=\"$cluster\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}}"
    }
   ]
  },
  {
   "title": "Read Latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rlatencyp95{by=\"cluster\", cluster=\"$cluster\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}} 95%"
    },
    {
     "expr": "rlatencyp99{by=\"cluster\", cluster=\"$cluster\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}} 99%"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "dc" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Information for $dc</h1>"
  },
  {
   "title": "Load",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{cluster=~\"$cluster\", dc=~\"$dc\"} )"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "Disk percente usage",
   "gridPos": { "h": 6, "w": 3, "x": 1, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_filesystem_avail_bytes{mountpoint=\"$mount_point\",  dc=~\"$dc\"})/(node_filesystem_size_bytes{mountpoint=\"$mount_point\", dc=~\"$dc\"})",
     "legendFormat": "{{dc}} {{instance}}"
    }
   ]
  },
  {
   "title": "Running Compactions",
   "type": "timeseries",
   "description": "Holds the number of currently active compactions.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(scylla_compaction_manager_compactions{cluster=\"$cluster\", dc=~\"$dc\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Cache Hits/Misses",
   "type": "timeseries",
   "description": "The Hits and Misses",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_row_hits{cluster=\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Hit {{instance}}"
    },
    {
     "expr": "sum(rate(scylla_cache_row_misses{cluster=\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Misses {{instance}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 17, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "0*scylla_scylladb_current_version{cluster=\"$cluster\", dc=~\"$dc\"} + on (instance) group_left() (scylla_node_operation_mode{cluster=\"$cluster\", dc=~\"$dc\"}!= 3 or on (instance) ((scylla_gossip_live{cluster=\"$cluster\", dc=~\"$dc\"}+1<  bool scalar(count(scylla_node_operation_mode{cluster=\"$cluster\"}==3)))*6 + 3))"
    },
    {
     "expr": "avg(scylla_reactor_utilization{cluster=~\"$cluster\", dc=~\"$dc\"} ) by (instance)"
    },
    {
     "expr": "sum(rate(scylla_reactor_aio_errors{cluster=~\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by (instance)"
    },
    {
     "expr": "sum(scylla_errors:nodes_total{cluster=~\"$cluster\", dc=~\"$dc\"}) by (instance) >bool 0"
    },
    {
     "expr": "(sum(scylla_cql:non_system_prepared1m{cluster=~\"$cluster\", dc=~\"$dc\"}) by (instance) >bool 1) + (sum(rate(scylla_cql_reverse_queries{cluster=~\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by(instance) >bool 1) + (sum(scylla_cql:non_paged_no_system1m{cluster=~\"$cluster\", dc=~\"$dc\"}) by (instance) >bool 1)"
    },
    {
     "expr": "100-100*node_filesystem_avail_bytes{mountpoint=\"$mount_point\",  dc=~\"$dc\"}/node_filesystem_size_bytes{mountpoint=\"$mount_point\", dc=~\"$dc\"}"
    },
    {
     "expr": "(min(scylla_streaming_finished_percentage{cluster=\"$cluster\", dc=~\"$dc\"}*100) by (instance) < 100) or on (instance) (min(scylla_node_ops_finished_percentage{cluster=\"$cluster\", dc=~\"$dc\"}*100) by (instance) < 100) or on (instance)  0*sum(scylla_scylladb_current_version{cluster=\"$cluster\", dc=~\"$dc\"}) by (instance)"
    },
    {
     "expr": "count(scylla_reactor_utilization{cluster=~\"$cluster\", dc=~\"$dc\"} ) by (instance)"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"$mount_point\", dc=~\"$dc\"} - node_filesystem_avail_bytes{mountpoint=\"$mount_point\",  dc=~\"$dc\"}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "description": "Write attempts - include all writes that reached the coordinator node, even if they will eventually fail",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_latency_count{cluster=\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by ([[by]]) or on([[by]]) sum(rate(scylla_storage_proxy_coordinator_write_latency_summary_count{cluster=\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Writes {{instance}}"
    },
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_latency_count{cluster=\"$cluster\", dc=~\"$dc\"}[$__rate_interval] offset 1d)) or on ([[by]]) sum(rate(scylla_storage_proxy_coordinator_write_latency_summary_count{cluster=\"$cluster\", dc=~\"$dc\"}[$__rate_interval] offset 1d))",
     "legendFormat": "1 Day Ago"
    },
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_latency_count{cluster=\"$cluster\", dc=~\"$dc\"}[$__rate_interval] offset 1w)) or on ([[by]]) sum(rate(scylla_storage_proxy_coordinator_write_latency_summary_count{cluster=\"$cluster\", dc=~\"$dc\"}[$__rate_interval] offset 1w))",
     "legendFormat": "1 Week Ago"
    }
   ]
  },
  {
   "title": "Write Latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(wlatencyp95{by=\"[[by]]\", cluster=\"$cluster\", dc=~\"$dc\" ,scheduling_group_name=~\"$sg\"}>0) by (scheduling_group_name, [[by]])",
     "legendFormat": "{{scheduling_group_name}} 95% {{instance}}"
    },
    {
     "expr": "avg(wlatencyp99{by=\"[[by]]\", cluster=\"$cluster\", dc=~\"$dc\" ,scheduling_group_name=~\"$sg\"}>0) by (scheduling_group_name, [[by]])",
     "legendFormat": "{{scheduling_group_name}} 99% {{instance}}"
    }
   ]
  },
  {
   "title": "Write Timeouts by [[by]]",
   "type": "timeseries",
   "description": "Requests that Scylla tried to write but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_timeouts{cluster=\"$cluster\", dc=~\"$dc\" }[$__rate_interval])) by ([[by]])",
     "legendFormat": "Writes {{instance}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "description": "Read attempts - include all reads that reached the coordinator node, even if they will eventually fail",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_read_latency_count{cluster=\"$cluster\", dc=~\"$dc\",scheduling_group_name=~\"$sg\"}[$__rate_interval])) by ([[by]]) or on([[by]]) sum(rate(scylla_storage_proxy_coordinator_read_latency_summary_count{cluster=\"$cluster\", dc=~\"$dc\",scheduling_group_name=~\"$sg\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Reads {{instance}}"
    },
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_read_latency_count{cluster=\"$cluster\", dc=~\"$dc\",scheduling_group_name=~\"$sg\"}[$__rate_interval] offset 1d)) or on ([[by]]) sum(rate(scylla_storage_proxy_coordinator_read_latency_summary_count{cluster=\"$cluster\", dc=~\"$dc\",scheduling_group_name=~\"$sg\"}[$__rate_interval] offset 1d))",
     "legendFormat": "1 Day Ago"
    },
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_read_latency_count{cluster=\"$cluster\", dc=~\"$dc\",scheduling_group_name=~\"$sg\"}[$__rate_interval] offset 1w)) or on ([[by]]) sum(rate(scylla_storage_proxy_coordinator_read_latency_summary_count{cluster=\"$cluster\", dc=~\"$dc\",scheduling_group_name=~\"$sg\"}[$__rate_interval] offset 1w))",
     "legendFormat": "1 Week Ago"
    }
   ]
  },
  {
   "title": "Read Latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rlatencyp95{by=\"[[by]]\", cluster=\"$cluster\", dc=~\"$dc\" ,scheduling_group_name=~\"$sg\"}>0) by(scheduling_group_name, [[by]])",
     "legendFormat": "{{scheduling_group_name}} 95% {{instance}}"
    },
    {
     "expr": "avg(rlatencyp99{by=\"[[by]]\", cluster=\"$cluster\", dc=~\"$dc\" ,scheduling_group_name=~\"$sg\"}>0) by(scheduling_group_name, [[by]])",
     "legendFormat": "{{scheduling_group_name}} 99% {{instance}}"
    }
   ]
  },
  {
   "title": "Read Timeouts by [[by]]",
   "type": "timeseries",
   "description": "Requests that Scylla tried to read but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(rate(scylla_storage_proxy_coordinator_read_timeouts{cluster=\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by ([[by]]) or vector(0))+on([[by]]) (sum(rate(scylla_storage_proxy_coordinator_cas_read_timeouts{cluster=\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by ([[by]]) or vector(0))+on([[by]]) (sum(rate(scylla_storage_proxy_coordinator_range_timeouts{cluster=\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by ([[by]]) or vector(0))",
     "legendFormat": "Read {{dc}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 10, "x": 14, "y": 43 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  { "title": "Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 51 },
   "options": {
    "content": "<div style=\"color:#5780C1; border-bottom: 0px solid #5780C1;\">Scylla Monitoring version - master</div> <div style=\"\"><a href=\"https://github.com/scylladb/scylla-monitoring/issues/new?body=scylla-version%3D[[scylla_version]]%0Amonitoring-version%3D[[monitoring_version]]%0Adashboard%3D${__dashboard.uid}\" target=\"_blank\">\n<input title=\"Report an issue with Scylla Monitoring\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;Report an issue on this page&nbsp;\"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"/render/d/${__dashboard.uid}?orgId=1&from=${__from}&to=${__to}&width=1600&height=-1&kiosk\" target=\"_blank\" download=\"dashboard_${__dashboard.uid}-${__from:date:iso}.png\"><input title=\"Make a Screenshot\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;&nbsp;&nbsp;Screenshot&nbsp;&nbsp;&nbsp;\"></input></a></span></div><script type=\"text/javascript\">  window.heapReadyCb=window.heapReadyCb||[],window.heap=window.heap||[],heap.load=function(e,t){window.heap.envId=e,window.heap.clientConfig=t=t||{},window.heap.clientConfig.shouldFetchServerConfig=!1;var a=document.createElement(\"script\");a.type=\"text/javascript\",a.async=!0,a.src=\"https://cdn.us.heap-api.com/config/\"+e+\"/heap_config.js\";var r=document.getElementsByTagName(\"script\")[0];r.parentNode.insertBefore(a,r);var n=[\"init\",\"startTracking\",\"stopTracking\",\"track\",\"resetIdentity\",\"identify\",\"getSessionId\",\"getUserId\",\"getIdentity\",\"addUserProperties\",\"addEventProperties\",\"removeEventProperty\",\"clearEventProperties\",\"addAccountProperties\",\"addAdapter\",\"addTransformer\",\"addTransformerFn\",\"onReady\",\"addPageviewProperties\",\"removePageviewProperty\",\"clearPageviewProperties\",\"trackPageview\"],i=function(e){return function(){var t=Array.prototype.slice.call(arguments,0);window.heapReadyCb.push({name:e,fn:function(){heap[e]&&heap[e].apply(heap,t)}})}};for(var p=0;p<n.length;p++)heap[n[p]]=i(n[p])};  heap.load('2144880022');</script>"
   }
  }
 ]
}