// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

// ScyllaClusterListerExpansion allows custom methods to be added to
// ScyllaClusterLister.
type ScyllaClusterListerExpansion interface{}

// ScyllaClusterNamespaceListerExpansion allows custom methods to be added to
// ScyllaClusterNamespaceLister.
type ScyllaClusterNamespaceListerExpansion interface{}
