{{ if eq .Values.platform "openshift" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scylladb:controller:aggregate-to-operator-openshift
  labels:
    rbac.operator.scylladb.com/aggregate-to-scylla-operator: "true"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps/finalizers
  - secrets/finalizers
  - pods/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - scylla.scylladb.com
  resources:
  - scyllaclusters/finalizers
  - scylladbdatacenters/finalizers
  - scylladbmonitorings/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - scylla.scylladb.com
  resources:
  - nodeconfigs/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{ end }}
