apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: scylla
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: scylla
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: "external-prometheus"
  namespace: "scylla"
spec:
  version: "v3.5.0"
  serviceAccountName: "prometheus"
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    fsGroup: 65534
  web:
    pageTitle: "ScyllaDB Prometheus"
  serviceMonitorSelector:
    matchLabels:
      scylla-operator.scylladb.com/scylladbmonitoring-name: "scylla-monitoring"
  alerting:
    alertmanagers:
      - name: "scylla-monitoring"
        port: web
  ruleSelector:
    matchLabels:
      scylla-operator.scylladb.com/scylladbmonitoring-name: "scylla-monitoring"
