// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	scyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	scheme "github.com/scylladb/scylla-operator/pkg/client/scylla/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RemoteOwnersGetter has a method to return a RemoteOwnerInterface.
// A group's client should implement this interface.
type RemoteOwnersGetter interface {
	RemoteOwners(namespace string) RemoteOwnerInterface
}

// RemoteOwnerInterface has methods to work with RemoteOwner resources.
type RemoteOwnerInterface interface {
	Create(ctx context.Context, remoteOwner *scyllav1alpha1.RemoteOwner, opts v1.CreateOptions) (*scyllav1alpha1.RemoteOwner, error)
	Update(ctx context.Context, remoteOwner *scyllav1alpha1.RemoteOwner, opts v1.UpdateOptions) (*scyllav1alpha1.RemoteOwner, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*scyllav1alpha1.RemoteOwner, error)
	List(ctx context.Context, opts v1.ListOptions) (*scyllav1alpha1.RemoteOwnerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *scyllav1alpha1.RemoteOwner, err error)
	RemoteOwnerExpansion
}

// remoteOwners implements RemoteOwnerInterface
type remoteOwners struct {
	*gentype.ClientWithList[*scyllav1alpha1.RemoteOwner, *scyllav1alpha1.RemoteOwnerList]
}

// newRemoteOwners returns a RemoteOwners
func newRemoteOwners(c *ScyllaV1alpha1Client, namespace string) *remoteOwners {
	return &remoteOwners{
		gentype.NewClientWithList[*scyllav1alpha1.RemoteOwner, *scyllav1alpha1.RemoteOwnerList](
			"remoteowners",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *scyllav1alpha1.RemoteOwner { return &scyllav1alpha1.RemoteOwner{} },
			func() *scyllav1alpha1.RemoteOwnerList { return &scyllav1alpha1.RemoteOwnerList{} },
		),
	}
}
