#!/bin/bash

set -euxEo pipefail
shopt -s inherit_errexit

# This script synchronizes the `packageRules` in `renovate.json` with the `replace` directives in `go.mod`.
# It extracts LHS module paths from `go.mod` replace directives and updates the `matchPackageNames` array
# in the $packageRuleDescription package rule.

# Print usage information.
echo "Usage: ./sync-renovate-config-with-go-mod-replace.sh <target-renovate-config-file>"

# Validate there's one argument provided.
if [ "$#" -ne 1 ]; then
    echo "Error: Exactly one argument (target renovate config file) is required."
    exit 1
fi

readonly renovate_config_file="$1"
readonly packageRuleDescription="go.mod dependencies that should not be updated (rule auto-generated by make update-renovate-config)"

# Extract LHS module paths from go.mod replace directives using go mod edit -json and return as a JSON array.
modules_json="$(go mod edit -json | jq -r '.Replace[]?.Old.Path // empty' | sort | jq -R . | jq -s .)"

# Update renovate.json with the extracted modules using jq to update the matchPackageNames array in the specific packageRule.
jq --argjson modules "${modules_json}" '
    .packageRules = (
        .packageRules | map(
            if .description == "'"${packageRuleDescription}"'" then
                .matchPackageNames = $modules
            else
                .
            end
        )
    )
' "${renovate_config_file}" > "${renovate_config_file}.tmp"
mv "${renovate_config_file}.tmp" "${renovate_config_file}"

echo "Successfully updated ${renovate_config_file}"
