#!/usr/bin/env bash
#
# Copyright (C) 2026 ScyllaDB
#
# This script synchronizes the ScyllaDB test version fields in assets/config/config.yaml with the main ScyllaDB version.
#
# .operatorTests.scyllaDBVersions.updateFrom is set to the highest release lower than
# .operator.scyllaDBVersion within its minor, falling back to a release candidate of that version if
# no lower patch has been released yet.
#
# .operator.scyllaDBVersion can also be set manually to a release candidate, to test a minor which hasn't
# been released yet. When it's the first release candidate of its minor, there is nothing lower to generate
# updateFrom from, so the committed value is kept and a warning is printed - it has to be set manually by
# whoever pins the release candidate.
#
# .operatorTests.scyllaDBVersions.upgradeFrom is set to the highest release of one minor lower than
# .operator.scyllaDBVersion. It's only recomputed when it's not on that minor already, so that the
# value stays pinned and this script remains deterministic - the previous minor keeps receiving
# patches long after we bump, and following them would break verification of unrelated changes.

set -euxEo pipefail
shopt -s inherit_errexit

readonly script_dir="$( realpath $( dirname "${BASH_SOURCE[0]}" ) )"

readonly scylladb_repo_url="https://github.com/scylladb/scylladb.git"

source "${script_dir}/lib/semver.sh"

# Lists ScyllaDB releases and release candidates of the given minor, highest first.
# Other tags created by the release process, like build candidates, have no released image and don't match.
# $1 - minor version, e.g. "2026.2"
function list_releases {
  git ls-remote --tags --refs "${scylladb_repo_url}" "refs/tags/scylla-${1}.*" \
    | sed -e 's|^.*refs/tags/scylla-||' \
    | grep -E -e "^${1//./\\.}\.[0-9]+(-rc[0-9]+)?$" \
    | sort_semver_decs
}

if [[ "$#" -ne 1 ]]; then
  echo -e "Invalid arguments.\nUsage: ${0} <target_config_file>" >&2
  exit 1
fi

target_config_file="${1}"

scylladb_version="$( yq -e '.operator.scyllaDBVersion' "${target_config_file}" )"
if [[ ! "${scylladb_version}" =~ ^([0-9]+)\.([0-9]+)\. ]]; then
  echo "Error: .operator.scyllaDBVersion '${scylladb_version}' is not a valid release version" >&2
  exit 1
fi

readonly major_number="${BASH_REMATCH[1]}"
readonly minor_number="${BASH_REMATCH[2]}"

readonly current_minor="${major_number}.${minor_number}"
readonly previous_minor="${major_number}.$(( minor_number - 1 ))"

# find_previous_semver returns a non-zero status when there is nothing lower, which is handled below.
update_from="$( find_previous_semver "$( list_releases "${current_minor}" )" "${scylladb_version}" || true )"
if [[ -z "${update_from}" ]]; then
  # .operator.scyllaDBVersion can be set manually to a release candidate to test a minor which hasn't been
  # released yet, in which case there may be nothing lower within its minor. Keep the committed value - it
  # has to be chosen by whoever pins the release candidate.
  echo "Warning: Cannot find a ScyllaDB release lower than '${scylladb_version}' within minor '${current_minor}', keeping the committed .operatorTests.scyllaDBVersions.updateFrom" >&2
else
  update_from="${update_from}" yq -e -i '
    .operatorTests.scyllaDBVersions.updateFrom = env(update_from) | .operatorTests.scyllaDBVersions.updateFrom line_comment = "Generated by hack/sync-config-with-scylladb-test-versions.sh. One patch lower than .operator.scyllaDBVersion, or its highest release candidate if that minor has no lower patch yet. Has to be set manually when .operator.scyllaDBVersion is the first release candidate of its minor, as nothing lower exists to generate it from."
  ' "${target_config_file}"
fi

upgrade_from="$( yq -e '.operatorTests.scyllaDBVersions.upgradeFrom' "${target_config_file}" )"
if [[ ! "${upgrade_from}" =~ ^"${previous_minor}". ]]; then
  upgrade_from="$( list_releases "${previous_minor}" | head -n1 )"

  if [[ -z "${upgrade_from}" ]]; then
    echo "Error: Cannot find a ScyllaDB release for minor '${previous_minor}'" >&2
    exit 1
  fi
fi

upgrade_from="${upgrade_from}" yq -e -i '
  .operatorTests.scyllaDBVersions.upgradeFrom = env(upgrade_from) | .operatorTests.scyllaDBVersions.upgradeFrom line_comment = "Generated by hack/sync-config-with-scylladb-test-versions.sh. Highest release of one minor lower than .operator.scyllaDBVersion, only regenerated when it is not on that minor already."
' "${target_config_file}"
