// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	scyllav1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ScyllaClusterLister helps list ScyllaClusters.
// All objects returned here must be treated as read-only.
type ScyllaClusterLister interface {
	// List lists all ScyllaClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*scyllav1.ScyllaCluster, err error)
	// ScyllaClusters returns an object that can list and get ScyllaClusters.
	ScyllaClusters(namespace string) ScyllaClusterNamespaceLister
	ScyllaClusterListerExpansion
}

// scyllaClusterLister implements the ScyllaClusterLister interface.
type scyllaClusterLister struct {
	listers.ResourceIndexer[*scyllav1.ScyllaCluster]
}

// NewScyllaClusterLister returns a new ScyllaClusterLister.
func NewScyllaClusterLister(indexer cache.Indexer) ScyllaClusterLister {
	return &scyllaClusterLister{listers.New[*scyllav1.ScyllaCluster](indexer, scyllav1.Resource("scyllacluster"))}
}

// ScyllaClusters returns an object that can list and get ScyllaClusters.
func (s *scyllaClusterLister) ScyllaClusters(namespace string) ScyllaClusterNamespaceLister {
	return scyllaClusterNamespaceLister{listers.NewNamespaced[*scyllav1.ScyllaCluster](s.ResourceIndexer, namespace)}
}

// ScyllaClusterNamespaceLister helps list and get ScyllaClusters.
// All objects returned here must be treated as read-only.
type ScyllaClusterNamespaceLister interface {
	// List lists all ScyllaClusters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*scyllav1.ScyllaCluster, err error)
	// Get retrieves the ScyllaCluster from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*scyllav1.ScyllaCluster, error)
	ScyllaClusterNamespaceListerExpansion
}

// scyllaClusterNamespaceLister implements the ScyllaClusterNamespaceLister
// interface.
type scyllaClusterNamespaceLister struct {
	listers.ResourceIndexer[*scyllav1.ScyllaCluster]
}
