# This is a kind cluster configuration file used for testing the Scylla Operator.
# The kube-apiserver has the MutablePVNodeAffinity feature gate enabled to simulate PV orphaning in E2E tests.
# It gates PersistentVolume nodeAffinity update validation, which is evaluated by the kube-apiserver, so it
# doesn't have to be enabled on kubelet. It's alpha as of Kubernetes 1.35, hence it has to be enabled explicitly.
# Each node has:
# - the KubeletInUserNamespace feature gate enabled to allow running containers in user namespaces
# - a mount for a local containerd registry configuration
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  kubeProxyMode: "nftables"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            feature-gates: KubeletInUserNamespace=true
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            feature-gates: MutablePVNodeAffinity=true
    extraMounts:
      - hostPath: ./hack/kind/containerd-registries
        containerPath: /etc/containerd/certs.d
        readOnly: true
  # Two worker nodes dedicated to Scylla as that's the minimum required in tests.
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            feature-gates: KubeletInUserNamespace=true
            register-with-taints: "scylla-operator.scylladb.com/dedicated=scyllaclusters:NoSchedule"
    extraMounts:
      - hostPath: ./hack/kind/containerd-registries
        containerPath: /etc/containerd/certs.d
        readOnly: true
    labels:
      scylla.scylladb.com/node-type: scylla
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            feature-gates: KubeletInUserNamespace=true
            register-with-taints: "scylla-operator.scylladb.com/dedicated=scyllaclusters:NoSchedule"
    extraMounts:
      - hostPath: ./hack/kind/containerd-registries
        containerPath: /etc/containerd/certs.d
        readOnly: true
    labels:
      scylla.scylladb.com/node-type: scylla
  # One extra worker node for other components.
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            feature-gates: KubeletInUserNamespace=true
    extraMounts:
      - hostPath: ./hack/kind/containerd-registries
        containerPath: /etc/containerd/certs.d
        readOnly: true
