// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindConfigThriftMaxMessageLengthInMbParams creates a new FindConfigThriftMaxMessageLengthInMbParams object
// with the default values initialized.
func NewFindConfigThriftMaxMessageLengthInMbParams() *FindConfigThriftMaxMessageLengthInMbParams {

	return &FindConfigThriftMaxMessageLengthInMbParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindConfigThriftMaxMessageLengthInMbParamsWithTimeout creates a new FindConfigThriftMaxMessageLengthInMbParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindConfigThriftMaxMessageLengthInMbParamsWithTimeout(timeout time.Duration) *FindConfigThriftMaxMessageLengthInMbParams {

	return &FindConfigThriftMaxMessageLengthInMbParams{

		timeout: timeout,
	}
}

// NewFindConfigThriftMaxMessageLengthInMbParamsWithContext creates a new FindConfigThriftMaxMessageLengthInMbParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindConfigThriftMaxMessageLengthInMbParamsWithContext(ctx context.Context) *FindConfigThriftMaxMessageLengthInMbParams {

	return &FindConfigThriftMaxMessageLengthInMbParams{

		Context: ctx,
	}
}

// NewFindConfigThriftMaxMessageLengthInMbParamsWithHTTPClient creates a new FindConfigThriftMaxMessageLengthInMbParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindConfigThriftMaxMessageLengthInMbParamsWithHTTPClient(client *http.Client) *FindConfigThriftMaxMessageLengthInMbParams {

	return &FindConfigThriftMaxMessageLengthInMbParams{
		HTTPClient: client,
	}
}

/*FindConfigThriftMaxMessageLengthInMbParams contains all the parameters to send to the API endpoint
for the find config thrift max message length in mb operation typically these are written to a http.Request
*/
type FindConfigThriftMaxMessageLengthInMbParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find config thrift max message length in mb params
func (o *FindConfigThriftMaxMessageLengthInMbParams) WithTimeout(timeout time.Duration) *FindConfigThriftMaxMessageLengthInMbParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find config thrift max message length in mb params
func (o *FindConfigThriftMaxMessageLengthInMbParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find config thrift max message length in mb params
func (o *FindConfigThriftMaxMessageLengthInMbParams) WithContext(ctx context.Context) *FindConfigThriftMaxMessageLengthInMbParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find config thrift max message length in mb params
func (o *FindConfigThriftMaxMessageLengthInMbParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find config thrift max message length in mb params
func (o *FindConfigThriftMaxMessageLengthInMbParams) WithHTTPClient(client *http.Client) *FindConfigThriftMaxMessageLengthInMbParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find config thrift max message length in mb params
func (o *FindConfigThriftMaxMessageLengthInMbParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FindConfigThriftMaxMessageLengthInMbParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
