// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindConfigDynamicSnitchUpdateIntervalInMsParams creates a new FindConfigDynamicSnitchUpdateIntervalInMsParams object
// with the default values initialized.
func NewFindConfigDynamicSnitchUpdateIntervalInMsParams() *FindConfigDynamicSnitchUpdateIntervalInMsParams {

	return &FindConfigDynamicSnitchUpdateIntervalInMsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindConfigDynamicSnitchUpdateIntervalInMsParamsWithTimeout creates a new FindConfigDynamicSnitchUpdateIntervalInMsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindConfigDynamicSnitchUpdateIntervalInMsParamsWithTimeout(timeout time.Duration) *FindConfigDynamicSnitchUpdateIntervalInMsParams {

	return &FindConfigDynamicSnitchUpdateIntervalInMsParams{

		timeout: timeout,
	}
}

// NewFindConfigDynamicSnitchUpdateIntervalInMsParamsWithContext creates a new FindConfigDynamicSnitchUpdateIntervalInMsParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindConfigDynamicSnitchUpdateIntervalInMsParamsWithContext(ctx context.Context) *FindConfigDynamicSnitchUpdateIntervalInMsParams {

	return &FindConfigDynamicSnitchUpdateIntervalInMsParams{

		Context: ctx,
	}
}

// NewFindConfigDynamicSnitchUpdateIntervalInMsParamsWithHTTPClient creates a new FindConfigDynamicSnitchUpdateIntervalInMsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindConfigDynamicSnitchUpdateIntervalInMsParamsWithHTTPClient(client *http.Client) *FindConfigDynamicSnitchUpdateIntervalInMsParams {

	return &FindConfigDynamicSnitchUpdateIntervalInMsParams{
		HTTPClient: client,
	}
}

/*FindConfigDynamicSnitchUpdateIntervalInMsParams contains all the parameters to send to the API endpoint
for the find config dynamic snitch update interval in ms operation typically these are written to a http.Request
*/
type FindConfigDynamicSnitchUpdateIntervalInMsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find config dynamic snitch update interval in ms params
func (o *FindConfigDynamicSnitchUpdateIntervalInMsParams) WithTimeout(timeout time.Duration) *FindConfigDynamicSnitchUpdateIntervalInMsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find config dynamic snitch update interval in ms params
func (o *FindConfigDynamicSnitchUpdateIntervalInMsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find config dynamic snitch update interval in ms params
func (o *FindConfigDynamicSnitchUpdateIntervalInMsParams) WithContext(ctx context.Context) *FindConfigDynamicSnitchUpdateIntervalInMsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find config dynamic snitch update interval in ms params
func (o *FindConfigDynamicSnitchUpdateIntervalInMsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find config dynamic snitch update interval in ms params
func (o *FindConfigDynamicSnitchUpdateIntervalInMsParams) WithHTTPClient(client *http.Client) *FindConfigDynamicSnitchUpdateIntervalInMsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find config dynamic snitch update interval in ms params
func (o *FindConfigDynamicSnitchUpdateIntervalInMsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FindConfigDynamicSnitchUpdateIntervalInMsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
