// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindConfigCommitlogDirectoryParams creates a new FindConfigCommitlogDirectoryParams object
// with the default values initialized.
func NewFindConfigCommitlogDirectoryParams() *FindConfigCommitlogDirectoryParams {

	return &FindConfigCommitlogDirectoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindConfigCommitlogDirectoryParamsWithTimeout creates a new FindConfigCommitlogDirectoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindConfigCommitlogDirectoryParamsWithTimeout(timeout time.Duration) *FindConfigCommitlogDirectoryParams {

	return &FindConfigCommitlogDirectoryParams{

		timeout: timeout,
	}
}

// NewFindConfigCommitlogDirectoryParamsWithContext creates a new FindConfigCommitlogDirectoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindConfigCommitlogDirectoryParamsWithContext(ctx context.Context) *FindConfigCommitlogDirectoryParams {

	return &FindConfigCommitlogDirectoryParams{

		Context: ctx,
	}
}

// NewFindConfigCommitlogDirectoryParamsWithHTTPClient creates a new FindConfigCommitlogDirectoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindConfigCommitlogDirectoryParamsWithHTTPClient(client *http.Client) *FindConfigCommitlogDirectoryParams {

	return &FindConfigCommitlogDirectoryParams{
		HTTPClient: client,
	}
}

/*FindConfigCommitlogDirectoryParams contains all the parameters to send to the API endpoint
for the find config commitlog directory operation typically these are written to a http.Request
*/
type FindConfigCommitlogDirectoryParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find config commitlog directory params
func (o *FindConfigCommitlogDirectoryParams) WithTimeout(timeout time.Duration) *FindConfigCommitlogDirectoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find config commitlog directory params
func (o *FindConfigCommitlogDirectoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find config commitlog directory params
func (o *FindConfigCommitlogDirectoryParams) WithContext(ctx context.Context) *FindConfigCommitlogDirectoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find config commitlog directory params
func (o *FindConfigCommitlogDirectoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find config commitlog directory params
func (o *FindConfigCommitlogDirectoryParams) WithHTTPClient(client *http.Client) *FindConfigCommitlogDirectoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find config commitlog directory params
func (o *FindConfigCommitlogDirectoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FindConfigCommitlogDirectoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
