// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindConfigMemtableTotalSpaceInMbParams creates a new FindConfigMemtableTotalSpaceInMbParams object
// with the default values initialized.
func NewFindConfigMemtableTotalSpaceInMbParams() *FindConfigMemtableTotalSpaceInMbParams {

	return &FindConfigMemtableTotalSpaceInMbParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindConfigMemtableTotalSpaceInMbParamsWithTimeout creates a new FindConfigMemtableTotalSpaceInMbParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindConfigMemtableTotalSpaceInMbParamsWithTimeout(timeout time.Duration) *FindConfigMemtableTotalSpaceInMbParams {

	return &FindConfigMemtableTotalSpaceInMbParams{

		timeout: timeout,
	}
}

// NewFindConfigMemtableTotalSpaceInMbParamsWithContext creates a new FindConfigMemtableTotalSpaceInMbParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindConfigMemtableTotalSpaceInMbParamsWithContext(ctx context.Context) *FindConfigMemtableTotalSpaceInMbParams {

	return &FindConfigMemtableTotalSpaceInMbParams{

		Context: ctx,
	}
}

// NewFindConfigMemtableTotalSpaceInMbParamsWithHTTPClient creates a new FindConfigMemtableTotalSpaceInMbParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindConfigMemtableTotalSpaceInMbParamsWithHTTPClient(client *http.Client) *FindConfigMemtableTotalSpaceInMbParams {

	return &FindConfigMemtableTotalSpaceInMbParams{
		HTTPClient: client,
	}
}

/*FindConfigMemtableTotalSpaceInMbParams contains all the parameters to send to the API endpoint
for the find config memtable total space in mb operation typically these are written to a http.Request
*/
type FindConfigMemtableTotalSpaceInMbParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find config memtable total space in mb params
func (o *FindConfigMemtableTotalSpaceInMbParams) WithTimeout(timeout time.Duration) *FindConfigMemtableTotalSpaceInMbParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find config memtable total space in mb params
func (o *FindConfigMemtableTotalSpaceInMbParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find config memtable total space in mb params
func (o *FindConfigMemtableTotalSpaceInMbParams) WithContext(ctx context.Context) *FindConfigMemtableTotalSpaceInMbParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find config memtable total space in mb params
func (o *FindConfigMemtableTotalSpaceInMbParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find config memtable total space in mb params
func (o *FindConfigMemtableTotalSpaceInMbParams) WithHTTPClient(client *http.Client) *FindConfigMemtableTotalSpaceInMbParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find config memtable total space in mb params
func (o *FindConfigMemtableTotalSpaceInMbParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FindConfigMemtableTotalSpaceInMbParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
