// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindConfigAPIAddressParams creates a new FindConfigAPIAddressParams object
// with the default values initialized.
func NewFindConfigAPIAddressParams() *FindConfigAPIAddressParams {

	return &FindConfigAPIAddressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindConfigAPIAddressParamsWithTimeout creates a new FindConfigAPIAddressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindConfigAPIAddressParamsWithTimeout(timeout time.Duration) *FindConfigAPIAddressParams {

	return &FindConfigAPIAddressParams{

		timeout: timeout,
	}
}

// NewFindConfigAPIAddressParamsWithContext creates a new FindConfigAPIAddressParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindConfigAPIAddressParamsWithContext(ctx context.Context) *FindConfigAPIAddressParams {

	return &FindConfigAPIAddressParams{

		Context: ctx,
	}
}

// NewFindConfigAPIAddressParamsWithHTTPClient creates a new FindConfigAPIAddressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindConfigAPIAddressParamsWithHTTPClient(client *http.Client) *FindConfigAPIAddressParams {

	return &FindConfigAPIAddressParams{
		HTTPClient: client,
	}
}

/*FindConfigAPIAddressParams contains all the parameters to send to the API endpoint
for the find config api address operation typically these are written to a http.Request
*/
type FindConfigAPIAddressParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find config api address params
func (o *FindConfigAPIAddressParams) WithTimeout(timeout time.Duration) *FindConfigAPIAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find config api address params
func (o *FindConfigAPIAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find config api address params
func (o *FindConfigAPIAddressParams) WithContext(ctx context.Context) *FindConfigAPIAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find config api address params
func (o *FindConfigAPIAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find config api address params
func (o *FindConfigAPIAddressParams) WithHTTPClient(client *http.Client) *FindConfigAPIAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find config api address params
func (o *FindConfigAPIAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FindConfigAPIAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
