// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindConfigCommitFailurePolicyParams creates a new FindConfigCommitFailurePolicyParams object
// with the default values initialized.
func NewFindConfigCommitFailurePolicyParams() *FindConfigCommitFailurePolicyParams {

	return &FindConfigCommitFailurePolicyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindConfigCommitFailurePolicyParamsWithTimeout creates a new FindConfigCommitFailurePolicyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindConfigCommitFailurePolicyParamsWithTimeout(timeout time.Duration) *FindConfigCommitFailurePolicyParams {

	return &FindConfigCommitFailurePolicyParams{

		timeout: timeout,
	}
}

// NewFindConfigCommitFailurePolicyParamsWithContext creates a new FindConfigCommitFailurePolicyParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindConfigCommitFailurePolicyParamsWithContext(ctx context.Context) *FindConfigCommitFailurePolicyParams {

	return &FindConfigCommitFailurePolicyParams{

		Context: ctx,
	}
}

// NewFindConfigCommitFailurePolicyParamsWithHTTPClient creates a new FindConfigCommitFailurePolicyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindConfigCommitFailurePolicyParamsWithHTTPClient(client *http.Client) *FindConfigCommitFailurePolicyParams {

	return &FindConfigCommitFailurePolicyParams{
		HTTPClient: client,
	}
}

/*FindConfigCommitFailurePolicyParams contains all the parameters to send to the API endpoint
for the find config commit failure policy operation typically these are written to a http.Request
*/
type FindConfigCommitFailurePolicyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find config commit failure policy params
func (o *FindConfigCommitFailurePolicyParams) WithTimeout(timeout time.Duration) *FindConfigCommitFailurePolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find config commit failure policy params
func (o *FindConfigCommitFailurePolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find config commit failure policy params
func (o *FindConfigCommitFailurePolicyParams) WithContext(ctx context.Context) *FindConfigCommitFailurePolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find config commit failure policy params
func (o *FindConfigCommitFailurePolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find config commit failure policy params
func (o *FindConfigCommitFailurePolicyParams) WithHTTPClient(client *http.Client) *FindConfigCommitFailurePolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find config commit failure policy params
func (o *FindConfigCommitFailurePolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FindConfigCommitFailurePolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
