// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindConfigRPCRecvBuffSizeInBytesParams creates a new FindConfigRPCRecvBuffSizeInBytesParams object
// with the default values initialized.
func NewFindConfigRPCRecvBuffSizeInBytesParams() *FindConfigRPCRecvBuffSizeInBytesParams {

	return &FindConfigRPCRecvBuffSizeInBytesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindConfigRPCRecvBuffSizeInBytesParamsWithTimeout creates a new FindConfigRPCRecvBuffSizeInBytesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindConfigRPCRecvBuffSizeInBytesParamsWithTimeout(timeout time.Duration) *FindConfigRPCRecvBuffSizeInBytesParams {

	return &FindConfigRPCRecvBuffSizeInBytesParams{

		timeout: timeout,
	}
}

// NewFindConfigRPCRecvBuffSizeInBytesParamsWithContext creates a new FindConfigRPCRecvBuffSizeInBytesParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindConfigRPCRecvBuffSizeInBytesParamsWithContext(ctx context.Context) *FindConfigRPCRecvBuffSizeInBytesParams {

	return &FindConfigRPCRecvBuffSizeInBytesParams{

		Context: ctx,
	}
}

// NewFindConfigRPCRecvBuffSizeInBytesParamsWithHTTPClient creates a new FindConfigRPCRecvBuffSizeInBytesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindConfigRPCRecvBuffSizeInBytesParamsWithHTTPClient(client *http.Client) *FindConfigRPCRecvBuffSizeInBytesParams {

	return &FindConfigRPCRecvBuffSizeInBytesParams{
		HTTPClient: client,
	}
}

/*FindConfigRPCRecvBuffSizeInBytesParams contains all the parameters to send to the API endpoint
for the find config rpc recv buff size in bytes operation typically these are written to a http.Request
*/
type FindConfigRPCRecvBuffSizeInBytesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find config rpc recv buff size in bytes params
func (o *FindConfigRPCRecvBuffSizeInBytesParams) WithTimeout(timeout time.Duration) *FindConfigRPCRecvBuffSizeInBytesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find config rpc recv buff size in bytes params
func (o *FindConfigRPCRecvBuffSizeInBytesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find config rpc recv buff size in bytes params
func (o *FindConfigRPCRecvBuffSizeInBytesParams) WithContext(ctx context.Context) *FindConfigRPCRecvBuffSizeInBytesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find config rpc recv buff size in bytes params
func (o *FindConfigRPCRecvBuffSizeInBytesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find config rpc recv buff size in bytes params
func (o *FindConfigRPCRecvBuffSizeInBytesParams) WithHTTPClient(client *http.Client) *FindConfigRPCRecvBuffSizeInBytesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find config rpc recv buff size in bytes params
func (o *FindConfigRPCRecvBuffSizeInBytesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FindConfigRPCRecvBuffSizeInBytesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
