// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindConfigDiskFailurePolicyParams creates a new FindConfigDiskFailurePolicyParams object
// with the default values initialized.
func NewFindConfigDiskFailurePolicyParams() *FindConfigDiskFailurePolicyParams {

	return &FindConfigDiskFailurePolicyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindConfigDiskFailurePolicyParamsWithTimeout creates a new FindConfigDiskFailurePolicyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindConfigDiskFailurePolicyParamsWithTimeout(timeout time.Duration) *FindConfigDiskFailurePolicyParams {

	return &FindConfigDiskFailurePolicyParams{

		timeout: timeout,
	}
}

// NewFindConfigDiskFailurePolicyParamsWithContext creates a new FindConfigDiskFailurePolicyParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindConfigDiskFailurePolicyParamsWithContext(ctx context.Context) *FindConfigDiskFailurePolicyParams {

	return &FindConfigDiskFailurePolicyParams{

		Context: ctx,
	}
}

// NewFindConfigDiskFailurePolicyParamsWithHTTPClient creates a new FindConfigDiskFailurePolicyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindConfigDiskFailurePolicyParamsWithHTTPClient(client *http.Client) *FindConfigDiskFailurePolicyParams {

	return &FindConfigDiskFailurePolicyParams{
		HTTPClient: client,
	}
}

/*FindConfigDiskFailurePolicyParams contains all the parameters to send to the API endpoint
for the find config disk failure policy operation typically these are written to a http.Request
*/
type FindConfigDiskFailurePolicyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find config disk failure policy params
func (o *FindConfigDiskFailurePolicyParams) WithTimeout(timeout time.Duration) *FindConfigDiskFailurePolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find config disk failure policy params
func (o *FindConfigDiskFailurePolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find config disk failure policy params
func (o *FindConfigDiskFailurePolicyParams) WithContext(ctx context.Context) *FindConfigDiskFailurePolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find config disk failure policy params
func (o *FindConfigDiskFailurePolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find config disk failure policy params
func (o *FindConfigDiskFailurePolicyParams) WithHTTPClient(client *http.Client) *FindConfigDiskFailurePolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find config disk failure policy params
func (o *FindConfigDiskFailurePolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FindConfigDiskFailurePolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
