// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindConfigRequestTimeoutInMsParams creates a new FindConfigRequestTimeoutInMsParams object
// with the default values initialized.
func NewFindConfigRequestTimeoutInMsParams() *FindConfigRequestTimeoutInMsParams {

	return &FindConfigRequestTimeoutInMsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindConfigRequestTimeoutInMsParamsWithTimeout creates a new FindConfigRequestTimeoutInMsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindConfigRequestTimeoutInMsParamsWithTimeout(timeout time.Duration) *FindConfigRequestTimeoutInMsParams {

	return &FindConfigRequestTimeoutInMsParams{

		timeout: timeout,
	}
}

// NewFindConfigRequestTimeoutInMsParamsWithContext creates a new FindConfigRequestTimeoutInMsParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindConfigRequestTimeoutInMsParamsWithContext(ctx context.Context) *FindConfigRequestTimeoutInMsParams {

	return &FindConfigRequestTimeoutInMsParams{

		Context: ctx,
	}
}

// NewFindConfigRequestTimeoutInMsParamsWithHTTPClient creates a new FindConfigRequestTimeoutInMsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindConfigRequestTimeoutInMsParamsWithHTTPClient(client *http.Client) *FindConfigRequestTimeoutInMsParams {

	return &FindConfigRequestTimeoutInMsParams{
		HTTPClient: client,
	}
}

/*FindConfigRequestTimeoutInMsParams contains all the parameters to send to the API endpoint
for the find config request timeout in ms operation typically these are written to a http.Request
*/
type FindConfigRequestTimeoutInMsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find config request timeout in ms params
func (o *FindConfigRequestTimeoutInMsParams) WithTimeout(timeout time.Duration) *FindConfigRequestTimeoutInMsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find config request timeout in ms params
func (o *FindConfigRequestTimeoutInMsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find config request timeout in ms params
func (o *FindConfigRequestTimeoutInMsParams) WithContext(ctx context.Context) *FindConfigRequestTimeoutInMsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find config request timeout in ms params
func (o *FindConfigRequestTimeoutInMsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find config request timeout in ms params
func (o *FindConfigRequestTimeoutInMsParams) WithHTTPClient(client *http.Client) *FindConfigRequestTimeoutInMsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find config request timeout in ms params
func (o *FindConfigRequestTimeoutInMsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FindConfigRequestTimeoutInMsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
