// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCacheServiceMetricsCounterHitRateGetParams creates a new CacheServiceMetricsCounterHitRateGetParams object
// with the default values initialized.
func NewCacheServiceMetricsCounterHitRateGetParams() *CacheServiceMetricsCounterHitRateGetParams {

	return &CacheServiceMetricsCounterHitRateGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCacheServiceMetricsCounterHitRateGetParamsWithTimeout creates a new CacheServiceMetricsCounterHitRateGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCacheServiceMetricsCounterHitRateGetParamsWithTimeout(timeout time.Duration) *CacheServiceMetricsCounterHitRateGetParams {

	return &CacheServiceMetricsCounterHitRateGetParams{

		timeout: timeout,
	}
}

// NewCacheServiceMetricsCounterHitRateGetParamsWithContext creates a new CacheServiceMetricsCounterHitRateGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewCacheServiceMetricsCounterHitRateGetParamsWithContext(ctx context.Context) *CacheServiceMetricsCounterHitRateGetParams {

	return &CacheServiceMetricsCounterHitRateGetParams{

		Context: ctx,
	}
}

// NewCacheServiceMetricsCounterHitRateGetParamsWithHTTPClient creates a new CacheServiceMetricsCounterHitRateGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCacheServiceMetricsCounterHitRateGetParamsWithHTTPClient(client *http.Client) *CacheServiceMetricsCounterHitRateGetParams {

	return &CacheServiceMetricsCounterHitRateGetParams{
		HTTPClient: client,
	}
}

/*CacheServiceMetricsCounterHitRateGetParams contains all the parameters to send to the API endpoint
for the cache service metrics counter hit rate get operation typically these are written to a http.Request
*/
type CacheServiceMetricsCounterHitRateGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cache service metrics counter hit rate get params
func (o *CacheServiceMetricsCounterHitRateGetParams) WithTimeout(timeout time.Duration) *CacheServiceMetricsCounterHitRateGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cache service metrics counter hit rate get params
func (o *CacheServiceMetricsCounterHitRateGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cache service metrics counter hit rate get params
func (o *CacheServiceMetricsCounterHitRateGetParams) WithContext(ctx context.Context) *CacheServiceMetricsCounterHitRateGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cache service metrics counter hit rate get params
func (o *CacheServiceMetricsCounterHitRateGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cache service metrics counter hit rate get params
func (o *CacheServiceMetricsCounterHitRateGetParams) WithHTTPClient(client *http.Client) *CacheServiceMetricsCounterHitRateGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cache service metrics counter hit rate get params
func (o *CacheServiceMetricsCounterHitRateGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CacheServiceMetricsCounterHitRateGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
