// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCacheServiceMetricsKeyCapacityGetParams creates a new CacheServiceMetricsKeyCapacityGetParams object
// with the default values initialized.
func NewCacheServiceMetricsKeyCapacityGetParams() *CacheServiceMetricsKeyCapacityGetParams {

	return &CacheServiceMetricsKeyCapacityGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCacheServiceMetricsKeyCapacityGetParamsWithTimeout creates a new CacheServiceMetricsKeyCapacityGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCacheServiceMetricsKeyCapacityGetParamsWithTimeout(timeout time.Duration) *CacheServiceMetricsKeyCapacityGetParams {

	return &CacheServiceMetricsKeyCapacityGetParams{

		timeout: timeout,
	}
}

// NewCacheServiceMetricsKeyCapacityGetParamsWithContext creates a new CacheServiceMetricsKeyCapacityGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewCacheServiceMetricsKeyCapacityGetParamsWithContext(ctx context.Context) *CacheServiceMetricsKeyCapacityGetParams {

	return &CacheServiceMetricsKeyCapacityGetParams{

		Context: ctx,
	}
}

// NewCacheServiceMetricsKeyCapacityGetParamsWithHTTPClient creates a new CacheServiceMetricsKeyCapacityGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCacheServiceMetricsKeyCapacityGetParamsWithHTTPClient(client *http.Client) *CacheServiceMetricsKeyCapacityGetParams {

	return &CacheServiceMetricsKeyCapacityGetParams{
		HTTPClient: client,
	}
}

/*CacheServiceMetricsKeyCapacityGetParams contains all the parameters to send to the API endpoint
for the cache service metrics key capacity get operation typically these are written to a http.Request
*/
type CacheServiceMetricsKeyCapacityGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cache service metrics key capacity get params
func (o *CacheServiceMetricsKeyCapacityGetParams) WithTimeout(timeout time.Duration) *CacheServiceMetricsKeyCapacityGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cache service metrics key capacity get params
func (o *CacheServiceMetricsKeyCapacityGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cache service metrics key capacity get params
func (o *CacheServiceMetricsKeyCapacityGetParams) WithContext(ctx context.Context) *CacheServiceMetricsKeyCapacityGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cache service metrics key capacity get params
func (o *CacheServiceMetricsKeyCapacityGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cache service metrics key capacity get params
func (o *CacheServiceMetricsKeyCapacityGetParams) WithHTTPClient(client *http.Client) *CacheServiceMetricsKeyCapacityGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cache service metrics key capacity get params
func (o *CacheServiceMetricsKeyCapacityGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CacheServiceMetricsKeyCapacityGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
