// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCacheServiceMetricsRowEntriesGetParams creates a new CacheServiceMetricsRowEntriesGetParams object
// with the default values initialized.
func NewCacheServiceMetricsRowEntriesGetParams() *CacheServiceMetricsRowEntriesGetParams {

	return &CacheServiceMetricsRowEntriesGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCacheServiceMetricsRowEntriesGetParamsWithTimeout creates a new CacheServiceMetricsRowEntriesGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCacheServiceMetricsRowEntriesGetParamsWithTimeout(timeout time.Duration) *CacheServiceMetricsRowEntriesGetParams {

	return &CacheServiceMetricsRowEntriesGetParams{

		timeout: timeout,
	}
}

// NewCacheServiceMetricsRowEntriesGetParamsWithContext creates a new CacheServiceMetricsRowEntriesGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewCacheServiceMetricsRowEntriesGetParamsWithContext(ctx context.Context) *CacheServiceMetricsRowEntriesGetParams {

	return &CacheServiceMetricsRowEntriesGetParams{

		Context: ctx,
	}
}

// NewCacheServiceMetricsRowEntriesGetParamsWithHTTPClient creates a new CacheServiceMetricsRowEntriesGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCacheServiceMetricsRowEntriesGetParamsWithHTTPClient(client *http.Client) *CacheServiceMetricsRowEntriesGetParams {

	return &CacheServiceMetricsRowEntriesGetParams{
		HTTPClient: client,
	}
}

/*CacheServiceMetricsRowEntriesGetParams contains all the parameters to send to the API endpoint
for the cache service metrics row entries get operation typically these are written to a http.Request
*/
type CacheServiceMetricsRowEntriesGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cache service metrics row entries get params
func (o *CacheServiceMetricsRowEntriesGetParams) WithTimeout(timeout time.Duration) *CacheServiceMetricsRowEntriesGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cache service metrics row entries get params
func (o *CacheServiceMetricsRowEntriesGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cache service metrics row entries get params
func (o *CacheServiceMetricsRowEntriesGetParams) WithContext(ctx context.Context) *CacheServiceMetricsRowEntriesGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cache service metrics row entries get params
func (o *CacheServiceMetricsRowEntriesGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cache service metrics row entries get params
func (o *CacheServiceMetricsRowEntriesGetParams) WithHTTPClient(client *http.Client) *CacheServiceMetricsRowEntriesGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cache service metrics row entries get params
func (o *CacheServiceMetricsRowEntriesGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CacheServiceMetricsRowEntriesGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
