// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCacheServiceRowCacheCapacityPostParams creates a new CacheServiceRowCacheCapacityPostParams object
// with the default values initialized.
func NewCacheServiceRowCacheCapacityPostParams() *CacheServiceRowCacheCapacityPostParams {
	var ()
	return &CacheServiceRowCacheCapacityPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCacheServiceRowCacheCapacityPostParamsWithTimeout creates a new CacheServiceRowCacheCapacityPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCacheServiceRowCacheCapacityPostParamsWithTimeout(timeout time.Duration) *CacheServiceRowCacheCapacityPostParams {
	var ()
	return &CacheServiceRowCacheCapacityPostParams{

		timeout: timeout,
	}
}

// NewCacheServiceRowCacheCapacityPostParamsWithContext creates a new CacheServiceRowCacheCapacityPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewCacheServiceRowCacheCapacityPostParamsWithContext(ctx context.Context) *CacheServiceRowCacheCapacityPostParams {
	var ()
	return &CacheServiceRowCacheCapacityPostParams{

		Context: ctx,
	}
}

// NewCacheServiceRowCacheCapacityPostParamsWithHTTPClient creates a new CacheServiceRowCacheCapacityPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCacheServiceRowCacheCapacityPostParamsWithHTTPClient(client *http.Client) *CacheServiceRowCacheCapacityPostParams {
	var ()
	return &CacheServiceRowCacheCapacityPostParams{
		HTTPClient: client,
	}
}

/*CacheServiceRowCacheCapacityPostParams contains all the parameters to send to the API endpoint
for the cache service row cache capacity post operation typically these are written to a http.Request
*/
type CacheServiceRowCacheCapacityPostParams struct {

	/*Capacity
	  row cache capacity in mb

	*/
	Capacity string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cache service row cache capacity post params
func (o *CacheServiceRowCacheCapacityPostParams) WithTimeout(timeout time.Duration) *CacheServiceRowCacheCapacityPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cache service row cache capacity post params
func (o *CacheServiceRowCacheCapacityPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cache service row cache capacity post params
func (o *CacheServiceRowCacheCapacityPostParams) WithContext(ctx context.Context) *CacheServiceRowCacheCapacityPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cache service row cache capacity post params
func (o *CacheServiceRowCacheCapacityPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cache service row cache capacity post params
func (o *CacheServiceRowCacheCapacityPostParams) WithHTTPClient(client *http.Client) *CacheServiceRowCacheCapacityPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cache service row cache capacity post params
func (o *CacheServiceRowCacheCapacityPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCapacity adds the capacity to the cache service row cache capacity post params
func (o *CacheServiceRowCacheCapacityPostParams) WithCapacity(capacity string) *CacheServiceRowCacheCapacityPostParams {
	o.SetCapacity(capacity)
	return o
}

// SetCapacity adds the capacity to the cache service row cache capacity post params
func (o *CacheServiceRowCacheCapacityPostParams) SetCapacity(capacity string) {
	o.Capacity = capacity
}

// WriteToRequest writes these params to a swagger request
func (o *CacheServiceRowCacheCapacityPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param capacity
	qrCapacity := o.Capacity
	qCapacity := qrCapacity
	if qCapacity != "" {
		if err := r.SetQueryParam("capacity", qCapacity); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
