// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strings"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/scylladb/scylla-operator/pkg/scyllaclient/internal/scylla/models"
)

// ColumnFamilyMetricsWaitingOnFreeMemtableGetReader is a Reader for the ColumnFamilyMetricsWaitingOnFreeMemtableGet structure.
type ColumnFamilyMetricsWaitingOnFreeMemtableGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ColumnFamilyMetricsWaitingOnFreeMemtableGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewColumnFamilyMetricsWaitingOnFreeMemtableGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewColumnFamilyMetricsWaitingOnFreeMemtableGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewColumnFamilyMetricsWaitingOnFreeMemtableGetOK creates a ColumnFamilyMetricsWaitingOnFreeMemtableGetOK with default headers values
func NewColumnFamilyMetricsWaitingOnFreeMemtableGetOK() *ColumnFamilyMetricsWaitingOnFreeMemtableGetOK {
	return &ColumnFamilyMetricsWaitingOnFreeMemtableGetOK{}
}

/*
ColumnFamilyMetricsWaitingOnFreeMemtableGetOK handles this case with default header values.

ColumnFamilyMetricsWaitingOnFreeMemtableGetOK column family metrics waiting on free memtable get o k
*/
type ColumnFamilyMetricsWaitingOnFreeMemtableGetOK struct {
}

func (o *ColumnFamilyMetricsWaitingOnFreeMemtableGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewColumnFamilyMetricsWaitingOnFreeMemtableGetDefault creates a ColumnFamilyMetricsWaitingOnFreeMemtableGetDefault with default headers values
func NewColumnFamilyMetricsWaitingOnFreeMemtableGetDefault(code int) *ColumnFamilyMetricsWaitingOnFreeMemtableGetDefault {
	return &ColumnFamilyMetricsWaitingOnFreeMemtableGetDefault{
		_statusCode: code,
	}
}

/*
ColumnFamilyMetricsWaitingOnFreeMemtableGetDefault handles this case with default header values.

internal server error
*/
type ColumnFamilyMetricsWaitingOnFreeMemtableGetDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the column family metrics waiting on free memtable get default response
func (o *ColumnFamilyMetricsWaitingOnFreeMemtableGetDefault) Code() int {
	return o._statusCode
}

func (o *ColumnFamilyMetricsWaitingOnFreeMemtableGetDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *ColumnFamilyMetricsWaitingOnFreeMemtableGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

func (o *ColumnFamilyMetricsWaitingOnFreeMemtableGetDefault) Error() string {
	return fmt.Sprintf("agent [HTTP %d] %s", o._statusCode, strings.TrimRight(o.Payload.Message, "."))
}
