// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams creates a new ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams object
// with the default values initialized.
func NewColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams() *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams {
	var ()
	return &ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewColumnFamilyMetricsMemtableLiveDataSizeByNameGetParamsWithTimeout creates a new ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewColumnFamilyMetricsMemtableLiveDataSizeByNameGetParamsWithTimeout(timeout time.Duration) *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams {
	var ()
	return &ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams{

		timeout: timeout,
	}
}

// NewColumnFamilyMetricsMemtableLiveDataSizeByNameGetParamsWithContext creates a new ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewColumnFamilyMetricsMemtableLiveDataSizeByNameGetParamsWithContext(ctx context.Context) *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams {
	var ()
	return &ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams{

		Context: ctx,
	}
}

// NewColumnFamilyMetricsMemtableLiveDataSizeByNameGetParamsWithHTTPClient creates a new ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewColumnFamilyMetricsMemtableLiveDataSizeByNameGetParamsWithHTTPClient(client *http.Client) *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams {
	var ()
	return &ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams{
		HTTPClient: client,
	}
}

/*ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams contains all the parameters to send to the API endpoint
for the column family metrics memtable live data size by name get operation typically these are written to a http.Request
*/
type ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams struct {

	/*Name
	  The column family name in keyspace:name format

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the column family metrics memtable live data size by name get params
func (o *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams) WithTimeout(timeout time.Duration) *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the column family metrics memtable live data size by name get params
func (o *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the column family metrics memtable live data size by name get params
func (o *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams) WithContext(ctx context.Context) *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the column family metrics memtable live data size by name get params
func (o *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the column family metrics memtable live data size by name get params
func (o *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams) WithHTTPClient(client *http.Client) *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the column family metrics memtable live data size by name get params
func (o *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the column family metrics memtable live data size by name get params
func (o *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams) WithName(name string) *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the column family metrics memtable live data size by name get params
func (o *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ColumnFamilyMetricsMemtableLiveDataSizeByNameGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
