// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strings"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/scylladb/scylla-operator/pkg/scyllaclient/internal/scylla/models"
)

// ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetReader is a Reader for the ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGet structure.
type ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetOK creates a ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetOK with default headers values
func NewColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetOK() *ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetOK {
	return &ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetOK{}
}

/*ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetOK handles this case with default header values.

ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetOK column family metrics index summary off heap memory used by name get o k
*/
type ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetOK struct {
	Payload interface{}
}

func (o *ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetOK) GetPayload() interface{} {
	return o.Payload
}

func (o *ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetDefault creates a ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetDefault with default headers values
func NewColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetDefault(code int) *ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetDefault {
	return &ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetDefault{
		_statusCode: code,
	}
}

/*ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetDefault handles this case with default header values.

internal server error
*/
type ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the column family metrics index summary off heap memory used by name get default response
func (o *ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetDefault) Code() int {
	return o._statusCode
}

func (o *ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

func (o *ColumnFamilyMetricsIndexSummaryOffHeapMemoryUsedByNameGetDefault) Error() string {
	return fmt.Sprintf("agent [HTTP %d] %s", o._statusCode, strings.TrimRight(o.Payload.Message, "."))
}
