// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strings"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/scylladb/scylla-operator/pkg/scyllaclient/internal/scylla/models"
)

// CompactionManagerCompactionInfoGetReader is a Reader for the CompactionManagerCompactionInfoGet structure.
type CompactionManagerCompactionInfoGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CompactionManagerCompactionInfoGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCompactionManagerCompactionInfoGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCompactionManagerCompactionInfoGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCompactionManagerCompactionInfoGetOK creates a CompactionManagerCompactionInfoGetOK with default headers values
func NewCompactionManagerCompactionInfoGetOK() *CompactionManagerCompactionInfoGetOK {
	return &CompactionManagerCompactionInfoGetOK{}
}

/*
CompactionManagerCompactionInfoGetOK handles this case with default header values.

CompactionManagerCompactionInfoGetOK compaction manager compaction info get o k
*/
type CompactionManagerCompactionInfoGetOK struct {
	Payload []*models.CompactionInfo
}

func (o *CompactionManagerCompactionInfoGetOK) GetPayload() []*models.CompactionInfo {
	return o.Payload
}

func (o *CompactionManagerCompactionInfoGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCompactionManagerCompactionInfoGetDefault creates a CompactionManagerCompactionInfoGetDefault with default headers values
func NewCompactionManagerCompactionInfoGetDefault(code int) *CompactionManagerCompactionInfoGetDefault {
	return &CompactionManagerCompactionInfoGetDefault{
		_statusCode: code,
	}
}

/*
CompactionManagerCompactionInfoGetDefault handles this case with default header values.

internal server error
*/
type CompactionManagerCompactionInfoGetDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the compaction manager compaction info get default response
func (o *CompactionManagerCompactionInfoGetDefault) Code() int {
	return o._statusCode
}

func (o *CompactionManagerCompactionInfoGetDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *CompactionManagerCompactionInfoGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

func (o *CompactionManagerCompactionInfoGetDefault) Error() string {
	return fmt.Sprintf("agent [HTTP %d] %s", o._statusCode, strings.TrimRight(o.Payload.Message, "."))
}
