// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strings"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/scylladb/scylla-operator/pkg/scyllaclient/internal/scylla/models"
)

// FailureDetectorCountEndpointUpGetReader is a Reader for the FailureDetectorCountEndpointUpGet structure.
type FailureDetectorCountEndpointUpGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FailureDetectorCountEndpointUpGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFailureDetectorCountEndpointUpGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFailureDetectorCountEndpointUpGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFailureDetectorCountEndpointUpGetOK creates a FailureDetectorCountEndpointUpGetOK with default headers values
func NewFailureDetectorCountEndpointUpGetOK() *FailureDetectorCountEndpointUpGetOK {
	return &FailureDetectorCountEndpointUpGetOK{}
}

/*FailureDetectorCountEndpointUpGetOK handles this case with default header values.

FailureDetectorCountEndpointUpGetOK failure detector count endpoint up get o k
*/
type FailureDetectorCountEndpointUpGetOK struct {
	Payload int32
}

func (o *FailureDetectorCountEndpointUpGetOK) GetPayload() int32 {
	return o.Payload
}

func (o *FailureDetectorCountEndpointUpGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFailureDetectorCountEndpointUpGetDefault creates a FailureDetectorCountEndpointUpGetDefault with default headers values
func NewFailureDetectorCountEndpointUpGetDefault(code int) *FailureDetectorCountEndpointUpGetDefault {
	return &FailureDetectorCountEndpointUpGetDefault{
		_statusCode: code,
	}
}

/*FailureDetectorCountEndpointUpGetDefault handles this case with default header values.

internal server error
*/
type FailureDetectorCountEndpointUpGetDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the failure detector count endpoint up get default response
func (o *FailureDetectorCountEndpointUpGetDefault) Code() int {
	return o._statusCode
}

func (o *FailureDetectorCountEndpointUpGetDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *FailureDetectorCountEndpointUpGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

func (o *FailureDetectorCountEndpointUpGetDefault) Error() string {
	return fmt.Sprintf("agent [HTTP %d] %s", o._statusCode, strings.TrimRight(o.Payload.Message, "."))
}
