// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strings"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/scylladb/scylla-operator/pkg/scyllaclient/internal/scylla/models"
)

// GossiperAssassinateByAddrPostReader is a Reader for the GossiperAssassinateByAddrPost structure.
type GossiperAssassinateByAddrPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GossiperAssassinateByAddrPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGossiperAssassinateByAddrPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGossiperAssassinateByAddrPostDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGossiperAssassinateByAddrPostOK creates a GossiperAssassinateByAddrPostOK with default headers values
func NewGossiperAssassinateByAddrPostOK() *GossiperAssassinateByAddrPostOK {
	return &GossiperAssassinateByAddrPostOK{}
}

/*GossiperAssassinateByAddrPostOK handles this case with default header values.

GossiperAssassinateByAddrPostOK gossiper assassinate by addr post o k
*/
type GossiperAssassinateByAddrPostOK struct {
}

func (o *GossiperAssassinateByAddrPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGossiperAssassinateByAddrPostDefault creates a GossiperAssassinateByAddrPostDefault with default headers values
func NewGossiperAssassinateByAddrPostDefault(code int) *GossiperAssassinateByAddrPostDefault {
	return &GossiperAssassinateByAddrPostDefault{
		_statusCode: code,
	}
}

/*GossiperAssassinateByAddrPostDefault handles this case with default header values.

internal server error
*/
type GossiperAssassinateByAddrPostDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the gossiper assassinate by addr post default response
func (o *GossiperAssassinateByAddrPostDefault) Code() int {
	return o._statusCode
}

func (o *GossiperAssassinateByAddrPostDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *GossiperAssassinateByAddrPostDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

func (o *GossiperAssassinateByAddrPostDefault) Error() string {
	return fmt.Sprintf("agent [HTTP %d] %s", o._statusCode, strings.TrimRight(o.Payload.Message, "."))
}
