// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strings"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/scylladb/scylla-operator/pkg/scyllaclient/internal/scylla/models"
)

// GossiperGenerationNumberByAddrGetReader is a Reader for the GossiperGenerationNumberByAddrGet structure.
type GossiperGenerationNumberByAddrGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GossiperGenerationNumberByAddrGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGossiperGenerationNumberByAddrGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGossiperGenerationNumberByAddrGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGossiperGenerationNumberByAddrGetOK creates a GossiperGenerationNumberByAddrGetOK with default headers values
func NewGossiperGenerationNumberByAddrGetOK() *GossiperGenerationNumberByAddrGetOK {
	return &GossiperGenerationNumberByAddrGetOK{}
}

/*
GossiperGenerationNumberByAddrGetOK handles this case with default header values.

GossiperGenerationNumberByAddrGetOK gossiper generation number by addr get o k
*/
type GossiperGenerationNumberByAddrGetOK struct {
	Payload int32
}

func (o *GossiperGenerationNumberByAddrGetOK) GetPayload() int32 {
	return o.Payload
}

func (o *GossiperGenerationNumberByAddrGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGossiperGenerationNumberByAddrGetDefault creates a GossiperGenerationNumberByAddrGetDefault with default headers values
func NewGossiperGenerationNumberByAddrGetDefault(code int) *GossiperGenerationNumberByAddrGetDefault {
	return &GossiperGenerationNumberByAddrGetDefault{
		_statusCode: code,
	}
}

/*
GossiperGenerationNumberByAddrGetDefault handles this case with default header values.

internal server error
*/
type GossiperGenerationNumberByAddrGetDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the gossiper generation number by addr get default response
func (o *GossiperGenerationNumberByAddrGetDefault) Code() int {
	return o._statusCode
}

func (o *GossiperGenerationNumberByAddrGetDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *GossiperGenerationNumberByAddrGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

func (o *GossiperGenerationNumberByAddrGetDefault) Error() string {
	return fmt.Sprintf("agent [HTTP %d] %s", o._statusCode, strings.TrimRight(o.Payload.Message, "."))
}
