// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLsaCompactPostParams creates a new LsaCompactPostParams object
// with the default values initialized.
func NewLsaCompactPostParams() *LsaCompactPostParams {

	return &LsaCompactPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLsaCompactPostParamsWithTimeout creates a new LsaCompactPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLsaCompactPostParamsWithTimeout(timeout time.Duration) *LsaCompactPostParams {

	return &LsaCompactPostParams{

		timeout: timeout,
	}
}

// NewLsaCompactPostParamsWithContext creates a new LsaCompactPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewLsaCompactPostParamsWithContext(ctx context.Context) *LsaCompactPostParams {

	return &LsaCompactPostParams{

		Context: ctx,
	}
}

// NewLsaCompactPostParamsWithHTTPClient creates a new LsaCompactPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLsaCompactPostParamsWithHTTPClient(client *http.Client) *LsaCompactPostParams {

	return &LsaCompactPostParams{
		HTTPClient: client,
	}
}

/*LsaCompactPostParams contains all the parameters to send to the API endpoint
for the lsa compact post operation typically these are written to a http.Request
*/
type LsaCompactPostParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the lsa compact post params
func (o *LsaCompactPostParams) WithTimeout(timeout time.Duration) *LsaCompactPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lsa compact post params
func (o *LsaCompactPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lsa compact post params
func (o *LsaCompactPostParams) WithContext(ctx context.Context) *LsaCompactPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lsa compact post params
func (o *LsaCompactPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lsa compact post params
func (o *LsaCompactPostParams) WithHTTPClient(client *http.Client) *LsaCompactPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lsa compact post params
func (o *LsaCompactPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *LsaCompactPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
