// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMessagingServiceMessagesDroppedByVerGetParams creates a new MessagingServiceMessagesDroppedByVerGetParams object
// with the default values initialized.
func NewMessagingServiceMessagesDroppedByVerGetParams() *MessagingServiceMessagesDroppedByVerGetParams {

	return &MessagingServiceMessagesDroppedByVerGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMessagingServiceMessagesDroppedByVerGetParamsWithTimeout creates a new MessagingServiceMessagesDroppedByVerGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMessagingServiceMessagesDroppedByVerGetParamsWithTimeout(timeout time.Duration) *MessagingServiceMessagesDroppedByVerGetParams {

	return &MessagingServiceMessagesDroppedByVerGetParams{

		timeout: timeout,
	}
}

// NewMessagingServiceMessagesDroppedByVerGetParamsWithContext creates a new MessagingServiceMessagesDroppedByVerGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewMessagingServiceMessagesDroppedByVerGetParamsWithContext(ctx context.Context) *MessagingServiceMessagesDroppedByVerGetParams {

	return &MessagingServiceMessagesDroppedByVerGetParams{

		Context: ctx,
	}
}

// NewMessagingServiceMessagesDroppedByVerGetParamsWithHTTPClient creates a new MessagingServiceMessagesDroppedByVerGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMessagingServiceMessagesDroppedByVerGetParamsWithHTTPClient(client *http.Client) *MessagingServiceMessagesDroppedByVerGetParams {

	return &MessagingServiceMessagesDroppedByVerGetParams{
		HTTPClient: client,
	}
}

/*MessagingServiceMessagesDroppedByVerGetParams contains all the parameters to send to the API endpoint
for the messaging service messages dropped by ver get operation typically these are written to a http.Request
*/
type MessagingServiceMessagesDroppedByVerGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the messaging service messages dropped by ver get params
func (o *MessagingServiceMessagesDroppedByVerGetParams) WithTimeout(timeout time.Duration) *MessagingServiceMessagesDroppedByVerGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the messaging service messages dropped by ver get params
func (o *MessagingServiceMessagesDroppedByVerGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the messaging service messages dropped by ver get params
func (o *MessagingServiceMessagesDroppedByVerGetParams) WithContext(ctx context.Context) *MessagingServiceMessagesDroppedByVerGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the messaging service messages dropped by ver get params
func (o *MessagingServiceMessagesDroppedByVerGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the messaging service messages dropped by ver get params
func (o *MessagingServiceMessagesDroppedByVerGetParams) WithHTTPClient(client *http.Client) *MessagingServiceMessagesDroppedByVerGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the messaging service messages dropped by ver get params
func (o *MessagingServiceMessagesDroppedByVerGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *MessagingServiceMessagesDroppedByVerGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
