// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStorageServiceSnapshotsPostParams creates a new StorageServiceSnapshotsPostParams object
// with the default values initialized.
func NewStorageServiceSnapshotsPostParams() *StorageServiceSnapshotsPostParams {
	var ()
	return &StorageServiceSnapshotsPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStorageServiceSnapshotsPostParamsWithTimeout creates a new StorageServiceSnapshotsPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStorageServiceSnapshotsPostParamsWithTimeout(timeout time.Duration) *StorageServiceSnapshotsPostParams {
	var ()
	return &StorageServiceSnapshotsPostParams{

		timeout: timeout,
	}
}

// NewStorageServiceSnapshotsPostParamsWithContext creates a new StorageServiceSnapshotsPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewStorageServiceSnapshotsPostParamsWithContext(ctx context.Context) *StorageServiceSnapshotsPostParams {
	var ()
	return &StorageServiceSnapshotsPostParams{

		Context: ctx,
	}
}

// NewStorageServiceSnapshotsPostParamsWithHTTPClient creates a new StorageServiceSnapshotsPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStorageServiceSnapshotsPostParamsWithHTTPClient(client *http.Client) *StorageServiceSnapshotsPostParams {
	var ()
	return &StorageServiceSnapshotsPostParams{
		HTTPClient: client,
	}
}

/*StorageServiceSnapshotsPostParams contains all the parameters to send to the API endpoint
for the storage service snapshots post operation typically these are written to a http.Request
*/
type StorageServiceSnapshotsPostParams struct {

	/*Cf
	  the column family to snapshot

	*/
	Cf *string
	/*Kn
	  Comma seperated keyspaces name to snapshot

	*/
	Kn *string
	/*Tag
	  the tag given to the snapshot

	*/
	Tag *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the storage service snapshots post params
func (o *StorageServiceSnapshotsPostParams) WithTimeout(timeout time.Duration) *StorageServiceSnapshotsPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage service snapshots post params
func (o *StorageServiceSnapshotsPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage service snapshots post params
func (o *StorageServiceSnapshotsPostParams) WithContext(ctx context.Context) *StorageServiceSnapshotsPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage service snapshots post params
func (o *StorageServiceSnapshotsPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage service snapshots post params
func (o *StorageServiceSnapshotsPostParams) WithHTTPClient(client *http.Client) *StorageServiceSnapshotsPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage service snapshots post params
func (o *StorageServiceSnapshotsPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCf adds the cf to the storage service snapshots post params
func (o *StorageServiceSnapshotsPostParams) WithCf(cf *string) *StorageServiceSnapshotsPostParams {
	o.SetCf(cf)
	return o
}

// SetCf adds the cf to the storage service snapshots post params
func (o *StorageServiceSnapshotsPostParams) SetCf(cf *string) {
	o.Cf = cf
}

// WithKn adds the kn to the storage service snapshots post params
func (o *StorageServiceSnapshotsPostParams) WithKn(kn *string) *StorageServiceSnapshotsPostParams {
	o.SetKn(kn)
	return o
}

// SetKn adds the kn to the storage service snapshots post params
func (o *StorageServiceSnapshotsPostParams) SetKn(kn *string) {
	o.Kn = kn
}

// WithTag adds the tag to the storage service snapshots post params
func (o *StorageServiceSnapshotsPostParams) WithTag(tag *string) *StorageServiceSnapshotsPostParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the storage service snapshots post params
func (o *StorageServiceSnapshotsPostParams) SetTag(tag *string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *StorageServiceSnapshotsPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cf != nil {

		// query param cf
		var qrCf string
		if o.Cf != nil {
			qrCf = *o.Cf
		}
		qCf := qrCf
		if qCf != "" {
			if err := r.SetQueryParam("cf", qCf); err != nil {
				return err
			}
		}

	}

	if o.Kn != nil {

		// query param kn
		var qrKn string
		if o.Kn != nil {
			qrKn = *o.Kn
		}
		qKn := qrKn
		if qKn != "" {
			if err := r.SetQueryParam("kn", qKn); err != nil {
				return err
			}
		}

	}

	if o.Tag != nil {

		// query param tag
		var qrTag string
		if o.Tag != nil {
			qrTag = *o.Tag
		}
		qTag := qrTag
		if qTag != "" {
			if err := r.SetQueryParam("tag", qTag); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
