// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStorageServiceKeyspaceCleanupByKeyspacePostParams creates a new StorageServiceKeyspaceCleanupByKeyspacePostParams object
// with the default values initialized.
func NewStorageServiceKeyspaceCleanupByKeyspacePostParams() *StorageServiceKeyspaceCleanupByKeyspacePostParams {
	var ()
	return &StorageServiceKeyspaceCleanupByKeyspacePostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStorageServiceKeyspaceCleanupByKeyspacePostParamsWithTimeout creates a new StorageServiceKeyspaceCleanupByKeyspacePostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStorageServiceKeyspaceCleanupByKeyspacePostParamsWithTimeout(timeout time.Duration) *StorageServiceKeyspaceCleanupByKeyspacePostParams {
	var ()
	return &StorageServiceKeyspaceCleanupByKeyspacePostParams{

		timeout: timeout,
	}
}

// NewStorageServiceKeyspaceCleanupByKeyspacePostParamsWithContext creates a new StorageServiceKeyspaceCleanupByKeyspacePostParams object
// with the default values initialized, and the ability to set a context for a request
func NewStorageServiceKeyspaceCleanupByKeyspacePostParamsWithContext(ctx context.Context) *StorageServiceKeyspaceCleanupByKeyspacePostParams {
	var ()
	return &StorageServiceKeyspaceCleanupByKeyspacePostParams{

		Context: ctx,
	}
}

// NewStorageServiceKeyspaceCleanupByKeyspacePostParamsWithHTTPClient creates a new StorageServiceKeyspaceCleanupByKeyspacePostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStorageServiceKeyspaceCleanupByKeyspacePostParamsWithHTTPClient(client *http.Client) *StorageServiceKeyspaceCleanupByKeyspacePostParams {
	var ()
	return &StorageServiceKeyspaceCleanupByKeyspacePostParams{
		HTTPClient: client,
	}
}

/*StorageServiceKeyspaceCleanupByKeyspacePostParams contains all the parameters to send to the API endpoint
for the storage service keyspace cleanup by keyspace post operation typically these are written to a http.Request
*/
type StorageServiceKeyspaceCleanupByKeyspacePostParams struct {

	/*Cf
	  Comma seperated column family names

	*/
	Cf *string
	/*Keyspace
	  The keyspace to query about

	*/
	Keyspace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the storage service keyspace cleanup by keyspace post params
func (o *StorageServiceKeyspaceCleanupByKeyspacePostParams) WithTimeout(timeout time.Duration) *StorageServiceKeyspaceCleanupByKeyspacePostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage service keyspace cleanup by keyspace post params
func (o *StorageServiceKeyspaceCleanupByKeyspacePostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage service keyspace cleanup by keyspace post params
func (o *StorageServiceKeyspaceCleanupByKeyspacePostParams) WithContext(ctx context.Context) *StorageServiceKeyspaceCleanupByKeyspacePostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage service keyspace cleanup by keyspace post params
func (o *StorageServiceKeyspaceCleanupByKeyspacePostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage service keyspace cleanup by keyspace post params
func (o *StorageServiceKeyspaceCleanupByKeyspacePostParams) WithHTTPClient(client *http.Client) *StorageServiceKeyspaceCleanupByKeyspacePostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage service keyspace cleanup by keyspace post params
func (o *StorageServiceKeyspaceCleanupByKeyspacePostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCf adds the cf to the storage service keyspace cleanup by keyspace post params
func (o *StorageServiceKeyspaceCleanupByKeyspacePostParams) WithCf(cf *string) *StorageServiceKeyspaceCleanupByKeyspacePostParams {
	o.SetCf(cf)
	return o
}

// SetCf adds the cf to the storage service keyspace cleanup by keyspace post params
func (o *StorageServiceKeyspaceCleanupByKeyspacePostParams) SetCf(cf *string) {
	o.Cf = cf
}

// WithKeyspace adds the keyspace to the storage service keyspace cleanup by keyspace post params
func (o *StorageServiceKeyspaceCleanupByKeyspacePostParams) WithKeyspace(keyspace string) *StorageServiceKeyspaceCleanupByKeyspacePostParams {
	o.SetKeyspace(keyspace)
	return o
}

// SetKeyspace adds the keyspace to the storage service keyspace cleanup by keyspace post params
func (o *StorageServiceKeyspaceCleanupByKeyspacePostParams) SetKeyspace(keyspace string) {
	o.Keyspace = keyspace
}

// WriteToRequest writes these params to a swagger request
func (o *StorageServiceKeyspaceCleanupByKeyspacePostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cf != nil {

		// query param cf
		var qrCf string
		if o.Cf != nil {
			qrCf = *o.Cf
		}
		qCf := qrCf
		if qCf != "" {
			if err := r.SetQueryParam("cf", qCf); err != nil {
				return err
			}
		}

	}

	// path param keyspace
	if err := r.SetPathParam("keyspace", o.Keyspace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
