// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStorageServiceLoggingLevelGetParams creates a new StorageServiceLoggingLevelGetParams object
// with the default values initialized.
func NewStorageServiceLoggingLevelGetParams() *StorageServiceLoggingLevelGetParams {

	return &StorageServiceLoggingLevelGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStorageServiceLoggingLevelGetParamsWithTimeout creates a new StorageServiceLoggingLevelGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStorageServiceLoggingLevelGetParamsWithTimeout(timeout time.Duration) *StorageServiceLoggingLevelGetParams {

	return &StorageServiceLoggingLevelGetParams{

		timeout: timeout,
	}
}

// NewStorageServiceLoggingLevelGetParamsWithContext creates a new StorageServiceLoggingLevelGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewStorageServiceLoggingLevelGetParamsWithContext(ctx context.Context) *StorageServiceLoggingLevelGetParams {

	return &StorageServiceLoggingLevelGetParams{

		Context: ctx,
	}
}

// NewStorageServiceLoggingLevelGetParamsWithHTTPClient creates a new StorageServiceLoggingLevelGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStorageServiceLoggingLevelGetParamsWithHTTPClient(client *http.Client) *StorageServiceLoggingLevelGetParams {

	return &StorageServiceLoggingLevelGetParams{
		HTTPClient: client,
	}
}

/*StorageServiceLoggingLevelGetParams contains all the parameters to send to the API endpoint
for the storage service logging level get operation typically these are written to a http.Request
*/
type StorageServiceLoggingLevelGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the storage service logging level get params
func (o *StorageServiceLoggingLevelGetParams) WithTimeout(timeout time.Duration) *StorageServiceLoggingLevelGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage service logging level get params
func (o *StorageServiceLoggingLevelGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage service logging level get params
func (o *StorageServiceLoggingLevelGetParams) WithContext(ctx context.Context) *StorageServiceLoggingLevelGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage service logging level get params
func (o *StorageServiceLoggingLevelGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage service logging level get params
func (o *StorageServiceLoggingLevelGetParams) WithHTTPClient(client *http.Client) *StorageServiceLoggingLevelGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage service logging level get params
func (o *StorageServiceLoggingLevelGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *StorageServiceLoggingLevelGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
