// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStorageServiceSlowQueryPostParams creates a new StorageServiceSlowQueryPostParams object
// with the default values initialized.
func NewStorageServiceSlowQueryPostParams() *StorageServiceSlowQueryPostParams {
	var ()
	return &StorageServiceSlowQueryPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStorageServiceSlowQueryPostParamsWithTimeout creates a new StorageServiceSlowQueryPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStorageServiceSlowQueryPostParamsWithTimeout(timeout time.Duration) *StorageServiceSlowQueryPostParams {
	var ()
	return &StorageServiceSlowQueryPostParams{

		timeout: timeout,
	}
}

// NewStorageServiceSlowQueryPostParamsWithContext creates a new StorageServiceSlowQueryPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewStorageServiceSlowQueryPostParamsWithContext(ctx context.Context) *StorageServiceSlowQueryPostParams {
	var ()
	return &StorageServiceSlowQueryPostParams{

		Context: ctx,
	}
}

// NewStorageServiceSlowQueryPostParamsWithHTTPClient creates a new StorageServiceSlowQueryPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStorageServiceSlowQueryPostParamsWithHTTPClient(client *http.Client) *StorageServiceSlowQueryPostParams {
	var ()
	return &StorageServiceSlowQueryPostParams{
		HTTPClient: client,
	}
}

/*StorageServiceSlowQueryPostParams contains all the parameters to send to the API endpoint
for the storage service slow query post operation typically these are written to a http.Request
*/
type StorageServiceSlowQueryPostParams struct {

	/*Enable
	  set it to true to enable, anything else to disable

	*/
	Enable *bool
	/*Threshold
	  Slow query record threshold in microseconds

	*/
	Threshold *string
	/*TTL
	  TTL in seconds

	*/
	TTL *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the storage service slow query post params
func (o *StorageServiceSlowQueryPostParams) WithTimeout(timeout time.Duration) *StorageServiceSlowQueryPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage service slow query post params
func (o *StorageServiceSlowQueryPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage service slow query post params
func (o *StorageServiceSlowQueryPostParams) WithContext(ctx context.Context) *StorageServiceSlowQueryPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage service slow query post params
func (o *StorageServiceSlowQueryPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage service slow query post params
func (o *StorageServiceSlowQueryPostParams) WithHTTPClient(client *http.Client) *StorageServiceSlowQueryPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage service slow query post params
func (o *StorageServiceSlowQueryPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnable adds the enable to the storage service slow query post params
func (o *StorageServiceSlowQueryPostParams) WithEnable(enable *bool) *StorageServiceSlowQueryPostParams {
	o.SetEnable(enable)
	return o
}

// SetEnable adds the enable to the storage service slow query post params
func (o *StorageServiceSlowQueryPostParams) SetEnable(enable *bool) {
	o.Enable = enable
}

// WithThreshold adds the threshold to the storage service slow query post params
func (o *StorageServiceSlowQueryPostParams) WithThreshold(threshold *string) *StorageServiceSlowQueryPostParams {
	o.SetThreshold(threshold)
	return o
}

// SetThreshold adds the threshold to the storage service slow query post params
func (o *StorageServiceSlowQueryPostParams) SetThreshold(threshold *string) {
	o.Threshold = threshold
}

// WithTTL adds the ttl to the storage service slow query post params
func (o *StorageServiceSlowQueryPostParams) WithTTL(ttl *string) *StorageServiceSlowQueryPostParams {
	o.SetTTL(ttl)
	return o
}

// SetTTL adds the ttl to the storage service slow query post params
func (o *StorageServiceSlowQueryPostParams) SetTTL(ttl *string) {
	o.TTL = ttl
}

// WriteToRequest writes these params to a swagger request
func (o *StorageServiceSlowQueryPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Enable != nil {

		// query param enable
		var qrEnable bool
		if o.Enable != nil {
			qrEnable = *o.Enable
		}
		qEnable := swag.FormatBool(qrEnable)
		if qEnable != "" {
			if err := r.SetQueryParam("enable", qEnable); err != nil {
				return err
			}
		}

	}

	if o.Threshold != nil {

		// query param threshold
		var qrThreshold string
		if o.Threshold != nil {
			qrThreshold = *o.Threshold
		}
		qThreshold := qrThreshold
		if qThreshold != "" {
			if err := r.SetQueryParam("threshold", qThreshold); err != nil {
				return err
			}
		}

	}

	if o.TTL != nil {

		// query param ttl
		var qrTTL string
		if o.TTL != nil {
			qrTTL = *o.TTL
		}
		qTTL := qrTTL
		if qTTL != "" {
			if err := r.SetQueryParam("ttl", qTTL); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
