// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStorageServiceBatchSizeFailureThresholdPostParams creates a new StorageServiceBatchSizeFailureThresholdPostParams object
// with the default values initialized.
func NewStorageServiceBatchSizeFailureThresholdPostParams() *StorageServiceBatchSizeFailureThresholdPostParams {
	var ()
	return &StorageServiceBatchSizeFailureThresholdPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStorageServiceBatchSizeFailureThresholdPostParamsWithTimeout creates a new StorageServiceBatchSizeFailureThresholdPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStorageServiceBatchSizeFailureThresholdPostParamsWithTimeout(timeout time.Duration) *StorageServiceBatchSizeFailureThresholdPostParams {
	var ()
	return &StorageServiceBatchSizeFailureThresholdPostParams{

		timeout: timeout,
	}
}

// NewStorageServiceBatchSizeFailureThresholdPostParamsWithContext creates a new StorageServiceBatchSizeFailureThresholdPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewStorageServiceBatchSizeFailureThresholdPostParamsWithContext(ctx context.Context) *StorageServiceBatchSizeFailureThresholdPostParams {
	var ()
	return &StorageServiceBatchSizeFailureThresholdPostParams{

		Context: ctx,
	}
}

// NewStorageServiceBatchSizeFailureThresholdPostParamsWithHTTPClient creates a new StorageServiceBatchSizeFailureThresholdPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStorageServiceBatchSizeFailureThresholdPostParamsWithHTTPClient(client *http.Client) *StorageServiceBatchSizeFailureThresholdPostParams {
	var ()
	return &StorageServiceBatchSizeFailureThresholdPostParams{
		HTTPClient: client,
	}
}

/*StorageServiceBatchSizeFailureThresholdPostParams contains all the parameters to send to the API endpoint
for the storage service batch size failure threshold post operation typically these are written to a http.Request
*/
type StorageServiceBatchSizeFailureThresholdPostParams struct {

	/*Threshold
	  batch size debug threshold

	*/
	Threshold int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the storage service batch size failure threshold post params
func (o *StorageServiceBatchSizeFailureThresholdPostParams) WithTimeout(timeout time.Duration) *StorageServiceBatchSizeFailureThresholdPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage service batch size failure threshold post params
func (o *StorageServiceBatchSizeFailureThresholdPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage service batch size failure threshold post params
func (o *StorageServiceBatchSizeFailureThresholdPostParams) WithContext(ctx context.Context) *StorageServiceBatchSizeFailureThresholdPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage service batch size failure threshold post params
func (o *StorageServiceBatchSizeFailureThresholdPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage service batch size failure threshold post params
func (o *StorageServiceBatchSizeFailureThresholdPostParams) WithHTTPClient(client *http.Client) *StorageServiceBatchSizeFailureThresholdPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage service batch size failure threshold post params
func (o *StorageServiceBatchSizeFailureThresholdPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithThreshold adds the threshold to the storage service batch size failure threshold post params
func (o *StorageServiceBatchSizeFailureThresholdPostParams) WithThreshold(threshold int32) *StorageServiceBatchSizeFailureThresholdPostParams {
	o.SetThreshold(threshold)
	return o
}

// SetThreshold adds the threshold to the storage service batch size failure threshold post params
func (o *StorageServiceBatchSizeFailureThresholdPostParams) SetThreshold(threshold int32) {
	o.Threshold = threshold
}

// WriteToRequest writes these params to a swagger request
func (o *StorageServiceBatchSizeFailureThresholdPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param threshold
	qrThreshold := o.Threshold
	qThreshold := swag.FormatInt32(qrThreshold)
	if qThreshold != "" {
		if err := r.SetQueryParam("threshold", qThreshold); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
