// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStorageServiceRangeToEndpointMapByKeyspaceGetParams creates a new StorageServiceRangeToEndpointMapByKeyspaceGetParams object
// with the default values initialized.
func NewStorageServiceRangeToEndpointMapByKeyspaceGetParams() *StorageServiceRangeToEndpointMapByKeyspaceGetParams {
	var ()
	return &StorageServiceRangeToEndpointMapByKeyspaceGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStorageServiceRangeToEndpointMapByKeyspaceGetParamsWithTimeout creates a new StorageServiceRangeToEndpointMapByKeyspaceGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStorageServiceRangeToEndpointMapByKeyspaceGetParamsWithTimeout(timeout time.Duration) *StorageServiceRangeToEndpointMapByKeyspaceGetParams {
	var ()
	return &StorageServiceRangeToEndpointMapByKeyspaceGetParams{

		timeout: timeout,
	}
}

// NewStorageServiceRangeToEndpointMapByKeyspaceGetParamsWithContext creates a new StorageServiceRangeToEndpointMapByKeyspaceGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewStorageServiceRangeToEndpointMapByKeyspaceGetParamsWithContext(ctx context.Context) *StorageServiceRangeToEndpointMapByKeyspaceGetParams {
	var ()
	return &StorageServiceRangeToEndpointMapByKeyspaceGetParams{

		Context: ctx,
	}
}

// NewStorageServiceRangeToEndpointMapByKeyspaceGetParamsWithHTTPClient creates a new StorageServiceRangeToEndpointMapByKeyspaceGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStorageServiceRangeToEndpointMapByKeyspaceGetParamsWithHTTPClient(client *http.Client) *StorageServiceRangeToEndpointMapByKeyspaceGetParams {
	var ()
	return &StorageServiceRangeToEndpointMapByKeyspaceGetParams{
		HTTPClient: client,
	}
}

/*StorageServiceRangeToEndpointMapByKeyspaceGetParams contains all the parameters to send to the API endpoint
for the storage service range to endpoint map by keyspace get operation typically these are written to a http.Request
*/
type StorageServiceRangeToEndpointMapByKeyspaceGetParams struct {

	/*Keyspace
	  The keyspace to query about

	*/
	Keyspace string
	/*RPC
	  When set to true, return the rpc address

	*/
	RPC *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the storage service range to endpoint map by keyspace get params
func (o *StorageServiceRangeToEndpointMapByKeyspaceGetParams) WithTimeout(timeout time.Duration) *StorageServiceRangeToEndpointMapByKeyspaceGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage service range to endpoint map by keyspace get params
func (o *StorageServiceRangeToEndpointMapByKeyspaceGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage service range to endpoint map by keyspace get params
func (o *StorageServiceRangeToEndpointMapByKeyspaceGetParams) WithContext(ctx context.Context) *StorageServiceRangeToEndpointMapByKeyspaceGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage service range to endpoint map by keyspace get params
func (o *StorageServiceRangeToEndpointMapByKeyspaceGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage service range to endpoint map by keyspace get params
func (o *StorageServiceRangeToEndpointMapByKeyspaceGetParams) WithHTTPClient(client *http.Client) *StorageServiceRangeToEndpointMapByKeyspaceGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage service range to endpoint map by keyspace get params
func (o *StorageServiceRangeToEndpointMapByKeyspaceGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKeyspace adds the keyspace to the storage service range to endpoint map by keyspace get params
func (o *StorageServiceRangeToEndpointMapByKeyspaceGetParams) WithKeyspace(keyspace string) *StorageServiceRangeToEndpointMapByKeyspaceGetParams {
	o.SetKeyspace(keyspace)
	return o
}

// SetKeyspace adds the keyspace to the storage service range to endpoint map by keyspace get params
func (o *StorageServiceRangeToEndpointMapByKeyspaceGetParams) SetKeyspace(keyspace string) {
	o.Keyspace = keyspace
}

// WithRPC adds the rpc to the storage service range to endpoint map by keyspace get params
func (o *StorageServiceRangeToEndpointMapByKeyspaceGetParams) WithRPC(rpc *bool) *StorageServiceRangeToEndpointMapByKeyspaceGetParams {
	o.SetRPC(rpc)
	return o
}

// SetRPC adds the rpc to the storage service range to endpoint map by keyspace get params
func (o *StorageServiceRangeToEndpointMapByKeyspaceGetParams) SetRPC(rpc *bool) {
	o.RPC = rpc
}

// WriteToRequest writes these params to a swagger request
func (o *StorageServiceRangeToEndpointMapByKeyspaceGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param keyspace
	if err := r.SetPathParam("keyspace", o.Keyspace); err != nil {
		return err
	}

	if o.RPC != nil {

		// query param rpc
		var qrRPC bool
		if o.RPC != nil {
			qrRPC = *o.RPC
		}
		qRPC := swag.FormatBool(qrRPC)
		if qRPC != "" {
			if err := r.SetQueryParam("rpc", qRPC); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
