// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStorageServiceTokensEndpointGetParams creates a new StorageServiceTokensEndpointGetParams object
// with the default values initialized.
func NewStorageServiceTokensEndpointGetParams() *StorageServiceTokensEndpointGetParams {

	return &StorageServiceTokensEndpointGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStorageServiceTokensEndpointGetParamsWithTimeout creates a new StorageServiceTokensEndpointGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStorageServiceTokensEndpointGetParamsWithTimeout(timeout time.Duration) *StorageServiceTokensEndpointGetParams {

	return &StorageServiceTokensEndpointGetParams{

		timeout: timeout,
	}
}

// NewStorageServiceTokensEndpointGetParamsWithContext creates a new StorageServiceTokensEndpointGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewStorageServiceTokensEndpointGetParamsWithContext(ctx context.Context) *StorageServiceTokensEndpointGetParams {

	return &StorageServiceTokensEndpointGetParams{

		Context: ctx,
	}
}

// NewStorageServiceTokensEndpointGetParamsWithHTTPClient creates a new StorageServiceTokensEndpointGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStorageServiceTokensEndpointGetParamsWithHTTPClient(client *http.Client) *StorageServiceTokensEndpointGetParams {

	return &StorageServiceTokensEndpointGetParams{
		HTTPClient: client,
	}
}

/*StorageServiceTokensEndpointGetParams contains all the parameters to send to the API endpoint
for the storage service tokens endpoint get operation typically these are written to a http.Request
*/
type StorageServiceTokensEndpointGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the storage service tokens endpoint get params
func (o *StorageServiceTokensEndpointGetParams) WithTimeout(timeout time.Duration) *StorageServiceTokensEndpointGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage service tokens endpoint get params
func (o *StorageServiceTokensEndpointGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage service tokens endpoint get params
func (o *StorageServiceTokensEndpointGetParams) WithContext(ctx context.Context) *StorageServiceTokensEndpointGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage service tokens endpoint get params
func (o *StorageServiceTokensEndpointGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage service tokens endpoint get params
func (o *StorageServiceTokensEndpointGetParams) WithHTTPClient(client *http.Client) *StorageServiceTokensEndpointGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage service tokens endpoint get params
func (o *StorageServiceTokensEndpointGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *StorageServiceTokensEndpointGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
