// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strings"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/scylladb/scylla-operator/pkg/scyllaclient/internal/scylla/models"
)

// StorageServiceIncrementalBackupsGetReader is a Reader for the StorageServiceIncrementalBackupsGet structure.
type StorageServiceIncrementalBackupsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StorageServiceIncrementalBackupsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStorageServiceIncrementalBackupsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewStorageServiceIncrementalBackupsGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStorageServiceIncrementalBackupsGetOK creates a StorageServiceIncrementalBackupsGetOK with default headers values
func NewStorageServiceIncrementalBackupsGetOK() *StorageServiceIncrementalBackupsGetOK {
	return &StorageServiceIncrementalBackupsGetOK{}
}

/*
StorageServiceIncrementalBackupsGetOK handles this case with default header values.

StorageServiceIncrementalBackupsGetOK storage service incremental backups get o k
*/
type StorageServiceIncrementalBackupsGetOK struct {
	Payload bool
}

func (o *StorageServiceIncrementalBackupsGetOK) GetPayload() bool {
	return o.Payload
}

func (o *StorageServiceIncrementalBackupsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStorageServiceIncrementalBackupsGetDefault creates a StorageServiceIncrementalBackupsGetDefault with default headers values
func NewStorageServiceIncrementalBackupsGetDefault(code int) *StorageServiceIncrementalBackupsGetDefault {
	return &StorageServiceIncrementalBackupsGetDefault{
		_statusCode: code,
	}
}

/*
StorageServiceIncrementalBackupsGetDefault handles this case with default header values.

internal server error
*/
type StorageServiceIncrementalBackupsGetDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the storage service incremental backups get default response
func (o *StorageServiceIncrementalBackupsGetDefault) Code() int {
	return o._statusCode
}

func (o *StorageServiceIncrementalBackupsGetDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *StorageServiceIncrementalBackupsGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

func (o *StorageServiceIncrementalBackupsGetDefault) Error() string {
	return fmt.Sprintf("agent [HTTP %d] %s", o._statusCode, strings.TrimRight(o.Payload.Message, "."))
}
