// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStreamManagerMetricsIncomingByPeerGetParams creates a new StreamManagerMetricsIncomingByPeerGetParams object
// with the default values initialized.
func NewStreamManagerMetricsIncomingByPeerGetParams() *StreamManagerMetricsIncomingByPeerGetParams {
	var ()
	return &StreamManagerMetricsIncomingByPeerGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStreamManagerMetricsIncomingByPeerGetParamsWithTimeout creates a new StreamManagerMetricsIncomingByPeerGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStreamManagerMetricsIncomingByPeerGetParamsWithTimeout(timeout time.Duration) *StreamManagerMetricsIncomingByPeerGetParams {
	var ()
	return &StreamManagerMetricsIncomingByPeerGetParams{

		timeout: timeout,
	}
}

// NewStreamManagerMetricsIncomingByPeerGetParamsWithContext creates a new StreamManagerMetricsIncomingByPeerGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewStreamManagerMetricsIncomingByPeerGetParamsWithContext(ctx context.Context) *StreamManagerMetricsIncomingByPeerGetParams {
	var ()
	return &StreamManagerMetricsIncomingByPeerGetParams{

		Context: ctx,
	}
}

// NewStreamManagerMetricsIncomingByPeerGetParamsWithHTTPClient creates a new StreamManagerMetricsIncomingByPeerGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStreamManagerMetricsIncomingByPeerGetParamsWithHTTPClient(client *http.Client) *StreamManagerMetricsIncomingByPeerGetParams {
	var ()
	return &StreamManagerMetricsIncomingByPeerGetParams{
		HTTPClient: client,
	}
}

/*StreamManagerMetricsIncomingByPeerGetParams contains all the parameters to send to the API endpoint
for the stream manager metrics incoming by peer get operation typically these are written to a http.Request
*/
type StreamManagerMetricsIncomingByPeerGetParams struct {

	/*Peer
	  The stream peer

	*/
	Peer string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stream manager metrics incoming by peer get params
func (o *StreamManagerMetricsIncomingByPeerGetParams) WithTimeout(timeout time.Duration) *StreamManagerMetricsIncomingByPeerGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stream manager metrics incoming by peer get params
func (o *StreamManagerMetricsIncomingByPeerGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stream manager metrics incoming by peer get params
func (o *StreamManagerMetricsIncomingByPeerGetParams) WithContext(ctx context.Context) *StreamManagerMetricsIncomingByPeerGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stream manager metrics incoming by peer get params
func (o *StreamManagerMetricsIncomingByPeerGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stream manager metrics incoming by peer get params
func (o *StreamManagerMetricsIncomingByPeerGetParams) WithHTTPClient(client *http.Client) *StreamManagerMetricsIncomingByPeerGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stream manager metrics incoming by peer get params
func (o *StreamManagerMetricsIncomingByPeerGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPeer adds the peer to the stream manager metrics incoming by peer get params
func (o *StreamManagerMetricsIncomingByPeerGetParams) WithPeer(peer string) *StreamManagerMetricsIncomingByPeerGetParams {
	o.SetPeer(peer)
	return o
}

// SetPeer adds the peer to the stream manager metrics incoming by peer get params
func (o *StreamManagerMetricsIncomingByPeerGetParams) SetPeer(peer string) {
	o.Peer = peer
}

// WriteToRequest writes these params to a swagger request
func (o *StreamManagerMetricsIncomingByPeerGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param peer
	if err := r.SetPathParam("peer", o.Peer); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
