{
 "title": "Scylla Per Machine Metrics 2.3",
 "tags": [ "2.3" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(node_filesystem_avail, cluster)"
   },
   {
    "name": "dc",
    "label": "dc",
    "query": "label_values(node_filesystem_avail{cluster=~\"$cluster\"}, dc)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_filesystem_avail{cluster=~\"$cluster|$^\", dc=~\"$dc\"}, instance)"
   },
   { "name": "monitor_disk", "query": "node_disk_bytes_read" },
   { "name": "monitor_network_interface", "query": "node_network_receive_packets" },
   { "name": "mount_point", "label": "Mounnt path", "query": "node_filesystem_avail" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "content": "<img src=\"http://www.scylladb.com/wp-content/uploads/logo-scylla-white-simple.png\" height=\"70\">\n<hr style=\"border-top: 3px solid #5780c1;\">"
  },
  {
   "title": "Total Storage $node",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "repeat": "node",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_avail{mountpoint=\"$mount_point\", instance=~\"$node\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "(sum(node_filesystem_size{mountpoint=\"$mount_point\", instance=~\"$node\"})-sum(node_filesystem_avail{mountpoint=\"$mount_point\", instance=~\"$node\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Disk $monitor_disk</h1>"
  },
  {
   "title": "Disk Writes per Server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_writes_completed{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", device=\"$monitor_disk\"}[30s])) by (instance)"
    }
   ]
  },
  {
   "title": "Disk Reads per Server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", device=\"$monitor_disk\"}[30s])) by (instance)"
    }
   ]
  },
  {
   "title": "Disk Writes Bps per Server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_bytes_written{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", device=\"$monitor_disk\"}[30s])) by (instance)"
    }
   ]
  },
  {
   "title": "Disk Read Bps per Server",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_bytes_read{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", device=\"$monitor_disk\"}[30s])) by (instance)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Network $monitor_network_interface</h1>"
  },
  {
   "title": "Interface Rx Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_packets{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", device=\"$monitor_network_interface\"}[30s])) by (instance)"
    }
   ]
  },
  {
   "title": "Interface Tx Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_packets{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", device=\"$monitor_network_interface\"}[30s])) by (instance)"
    }
   ]
  },
  {
   "title": "Interface Rx Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", device=\"$monitor_network_interface\"}[30s])) by (instance)"
    }
   ]
  },
  {
   "title": "Interface Tx Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", device=\"$monitor_network_interface\"}[30s])) by (instance)"
    }
   ]
  }
 ]
}