// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// NodeConfigListerExpansion allows custom methods to be added to
// NodeConfigLister.
type NodeConfigListerExpansion interface{}

// ScyllaOperatorConfigListerExpansion allows custom methods to be added to
// ScyllaOperatorConfigLister.
type ScyllaOperatorConfigListerExpansion interface{}
