// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	scyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ScyllaDBStatusReportLister helps list ScyllaDBStatusReports.
// All objects returned here must be treated as read-only.
type ScyllaDBStatusReportLister interface {
	// List lists all ScyllaDBStatusReports in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*scyllav1alpha1.ScyllaDBStatusReport, err error)
	// ScyllaDBStatusReports returns an object that can list and get ScyllaDBStatusReports.
	ScyllaDBStatusReports(namespace string) ScyllaDBStatusReportNamespaceLister
	ScyllaDBStatusReportListerExpansion
}

// scyllaDBStatusReportLister implements the ScyllaDBStatusReportLister interface.
type scyllaDBStatusReportLister struct {
	listers.ResourceIndexer[*scyllav1alpha1.ScyllaDBStatusReport]
}

// NewScyllaDBStatusReportLister returns a new ScyllaDBStatusReportLister.
func NewScyllaDBStatusReportLister(indexer cache.Indexer) ScyllaDBStatusReportLister {
	return &scyllaDBStatusReportLister{listers.New[*scyllav1alpha1.ScyllaDBStatusReport](indexer, scyllav1alpha1.Resource("scylladbstatusreport"))}
}

// ScyllaDBStatusReports returns an object that can list and get ScyllaDBStatusReports.
func (s *scyllaDBStatusReportLister) ScyllaDBStatusReports(namespace string) ScyllaDBStatusReportNamespaceLister {
	return scyllaDBStatusReportNamespaceLister{listers.NewNamespaced[*scyllav1alpha1.ScyllaDBStatusReport](s.ResourceIndexer, namespace)}
}

// ScyllaDBStatusReportNamespaceLister helps list and get ScyllaDBStatusReports.
// All objects returned here must be treated as read-only.
type ScyllaDBStatusReportNamespaceLister interface {
	// List lists all ScyllaDBStatusReports in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*scyllav1alpha1.ScyllaDBStatusReport, err error)
	// Get retrieves the ScyllaDBStatusReport from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*scyllav1alpha1.ScyllaDBStatusReport, error)
	ScyllaDBStatusReportNamespaceListerExpansion
}

// scyllaDBStatusReportNamespaceLister implements the ScyllaDBStatusReportNamespaceLister
// interface.
type scyllaDBStatusReportNamespaceLister struct {
	listers.ResourceIndexer[*scyllav1alpha1.ScyllaDBStatusReport]
}
