// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	scyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ScyllaDBManagerClusterRegistrationLister helps list ScyllaDBManagerClusterRegistrations.
// All objects returned here must be treated as read-only.
type ScyllaDBManagerClusterRegistrationLister interface {
	// List lists all ScyllaDBManagerClusterRegistrations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*scyllav1alpha1.ScyllaDBManagerClusterRegistration, err error)
	// ScyllaDBManagerClusterRegistrations returns an object that can list and get ScyllaDBManagerClusterRegistrations.
	ScyllaDBManagerClusterRegistrations(namespace string) ScyllaDBManagerClusterRegistrationNamespaceLister
	ScyllaDBManagerClusterRegistrationListerExpansion
}

// scyllaDBManagerClusterRegistrationLister implements the ScyllaDBManagerClusterRegistrationLister interface.
type scyllaDBManagerClusterRegistrationLister struct {
	listers.ResourceIndexer[*scyllav1alpha1.ScyllaDBManagerClusterRegistration]
}

// NewScyllaDBManagerClusterRegistrationLister returns a new ScyllaDBManagerClusterRegistrationLister.
func NewScyllaDBManagerClusterRegistrationLister(indexer cache.Indexer) ScyllaDBManagerClusterRegistrationLister {
	return &scyllaDBManagerClusterRegistrationLister{listers.New[*scyllav1alpha1.ScyllaDBManagerClusterRegistration](indexer, scyllav1alpha1.Resource("scylladbmanagerclusterregistration"))}
}

// ScyllaDBManagerClusterRegistrations returns an object that can list and get ScyllaDBManagerClusterRegistrations.
func (s *scyllaDBManagerClusterRegistrationLister) ScyllaDBManagerClusterRegistrations(namespace string) ScyllaDBManagerClusterRegistrationNamespaceLister {
	return scyllaDBManagerClusterRegistrationNamespaceLister{listers.NewNamespaced[*scyllav1alpha1.ScyllaDBManagerClusterRegistration](s.ResourceIndexer, namespace)}
}

// ScyllaDBManagerClusterRegistrationNamespaceLister helps list and get ScyllaDBManagerClusterRegistrations.
// All objects returned here must be treated as read-only.
type ScyllaDBManagerClusterRegistrationNamespaceLister interface {
	// List lists all ScyllaDBManagerClusterRegistrations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*scyllav1alpha1.ScyllaDBManagerClusterRegistration, err error)
	// Get retrieves the ScyllaDBManagerClusterRegistration from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*scyllav1alpha1.ScyllaDBManagerClusterRegistration, error)
	ScyllaDBManagerClusterRegistrationNamespaceListerExpansion
}

// scyllaDBManagerClusterRegistrationNamespaceLister implements the ScyllaDBManagerClusterRegistrationNamespaceLister
// interface.
type scyllaDBManagerClusterRegistrationNamespaceLister struct {
	listers.ResourceIndexer[*scyllav1alpha1.ScyllaDBManagerClusterRegistration]
}
