kind: DaemonSet
apiVersion: apps/v1
metadata:
  namespace: local-csi-driver
  name: local-csi-driver
  labels:
    app.kubernetes.io/name: local-csi-driver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: local-csi-driver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local-csi-driver
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        scylla.scylladb.com/node-type: scylla
      serviceAccountName: local-csi-driver
      tolerations:
      - operator: Exists
      containers:
      - name: local-csi-driver
        securityContext:
          privileged: true
        # renovate: datasource=docker depName=local-csi-driver packageName=docker.io/scylladb/local-csi-driver versioning=semver
        image: docker.io/scylladb/local-csi-driver:1.0.0-rc.3@sha256:a80212705a6cfbc2e7115b276d0ace1bfe88bcdc56b1e20732a64a4e6c1af4ff
        imagePullPolicy: IfNotPresent
        args:
        - --listen=/csi/csi.sock
        - --node-name=$(NODE_NAME)
        - --volumes-dir=/var/lib/persistent-volumes
        - --v=2
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: kubelet-dir
          mountPath: /var/lib/kubelet
          mountPropagation: "Bidirectional"
        - name: plugin-dir
          mountPath: /csi
        - name: volumes-dir
          mountPath: /var/lib/persistent-volumes
        ports:
        - name: healthz
          containerPort: 9809
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 2
          failureThreshold: 5
      - name: csi-driver-registrar
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.17.0@sha256:f9de845b170155199f2a2a3f9531cf13d78e31235e9db6b6582a8b0db0a50dad
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/local.csi.scylladb.com/csi.sock
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
        - name: registration-dir
          mountPath: /registration
      - name: liveness-probe
        image: registry.k8s.io/sig-storage/livenessprobe:v2.19.0@sha256:06da0d5b8908072f2e4522692aee8dc119fba7247a9658497e1153992cd777e9
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=/csi/csi.sock
        - --health-port=9809
        - --v=2
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
      - name: csi-provisioner
        image: registry.k8s.io/sig-storage/csi-provisioner:v5.3.0@sha256:bb057f866177d5f4139a1527e594499cbe0feeb67b63aaca8679dfdf0a6016f9
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=/csi/csi.sock
        - --v=2
        - --node-deployment
        - --immediate-topology=false
        - --enable-capacity
        - --capacity-ownerref-level=0
        - --capacity-poll-interval=30s
        - --default-fstype=xfs
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
      volumes:
      - name: kubelet-dir
        hostPath:
          path: /var/lib/kubelet
          type: Directory
      - name: plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins/local.csi.scylladb.com/
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
      - name: volumes-dir
        hostPath:
          path: /var/lib/persistent-volumes
          type: Directory
