{
 "title": "Overview",
 "tags": [ "6.2" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "by",
    "label": "by",
    "query": "Cluster : cluster,DC : dc, Instance : instance, Shard : instance\\,shard"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(scylla_reactor_utilization, cluster)"
   },
   {
    "name": "dc",
    "label": "dc",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster\"}, dc)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(scylla_reactor_utilization{cluster=\"$cluster\", dc=~\"$dc\"}, instance)"
   },
   {
    "name": "shard",
    "label": "shard",
    "query": "label_values(scylla_reactor_utilization{cluster=\"$cluster\"},shard)"
   },
   { "name": "mount_point", "label": "Mount path", "query": "node_filesystem_avail_bytes" },
   {
    "name": "sg",
    "label": "SG",
    "query": "label_values(scylla_scheduler_runtime_ms{cluster=~\"$cluster\", group!~\"atexit|gossip|mem_compaction|memtable|streaming|background_reclaim|compaction|main|memtable_to_cache\"},group)"
   },
   { "name": "func", "label": "Function", "query": "sum,avg,max,min,stddev,stdvar" },
   { "name": "dash_version", "query": "6-2" },
   {
    "name": "all_scyllas_versions",
    "query": "label_values(scylla_scylladb_current_version{cluster=\"$cluster\"}, version)"
   },
   {
    "name": "count_dc",
    "query": {
     "query": "query_result(count(up{job=~\"$cluster|$^\"}) by (dc))"
    }
   },
   { "name": "scylla_version", "query": "6.2" },
   { "name": "monitoring_version", "query": "4.8.3" }
  ]
 },
 "panels": [
  { "title": "Cluster overview $cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://repositories.scylladb.com/scylla/imgversion/$monitoring_version/scylla-monitoring\">"
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 4, "x": 9, "y": 1 }, "options": { "content": "# " } },
  { "type": "text", "gridPos": { "h": 1, "w": 4, "x": 13, "y": 1 }, "options": { "content": "# " } },
  { "type": "text", "gridPos": { "h": 1, "w": 7, "x": 17, "y": 1 }, "options": { "content": "# " } },
  {
   "title": "# Nodes",
   "type": "stat",
   "description": "The number of nodes configured in the cluster.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(scylla_scylladb_current_version{job=~\"$cluster|$^\", cluster=\"$cluster\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "stat",
   "description": "The number of unreachable nodes.\nUsually because a machine is down or unreachable.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(scrape_samples_scraped{job=~\"$cluster|$^\", cluster=\"$cluster\"}==0) OR vector(0))",
     "legendFormat": "Offline "
    }
   ]
  },
  {
   "title": "Inactive",
   "type": "stat",
   "description": "The number of joining and leaving nodes.\nThe number of nodes that are up but not actively part of the cluster, either because they are still joining or because they are leaving.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(scylla_node_operation_mode{cluster=\"$cluster\"}!=3)OR vector(0)",
     "legendFormat": "Offline "
    }
   ]
  },
  {
   "title": "Manager",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(max(scylla_manager_scheduler_run_indicator{type=~\"repair\",cluster=\"$cluster\"}) or on() vector(0)) + (max(scylla_manager_scheduler_run_indicator{type=~\"backup\",cluster=\"$cluster\"})*2 or on() vector(0)) + (sum(scylla_manager_server_current_version{}) or on() vector(-1))"
    },
    {
     "expr": "(avg(scylla_manager_repair_progress{cluster=\"$cluster\", job=\"scylla_manager\"}) * max(scylla_manager_scheduler_run_indicator{type=\"repair\",cluster=\"$cluster\"})) or on ()  (100*avg(manager:backup_progress{cluster=\"$cluster\"}) * max(scylla_manager_scheduler_run_indicator{type=\"backup\",cluster=\"$cluster\"})) or on () vector(0)"
    }
   ]
  },
  {
   "title": "Avg Write",
   "type": "stat",
   "description": "Average Write Latency",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(wlatencya{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0)"
    }
   ]
  },
  {
   "title": "99% Write",
   "type": "stat",
   "description": "99% write Latency",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "wlatencyp99{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}}"
    }
   ]
  },
  {
   "title": "Avg Read",
   "type": "stat",
   "description": "Average Read Latency",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rlatencya{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0)"
    }
   ]
  },
  {
   "title": "99% Read",
   "type": "stat",
   "description": "99% read Latency",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rlatencyp99{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}}"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "si:" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(scylla_transport_requests_served{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) + (sum(rate(scylla_thrift_served{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) or on() vector(0))"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "description": "The percentage of the time during which Scylla utilized the CPU. Note that because Scylla does busy polling for some time before going idle, CPU utilization as seen by the operating system may be much higher. Your system is not yet CPU-bottlenecked until this metric is high.",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"} )"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "stat",
   "description": "The rate of timeouts (read and write).\n\nTimeouts are an indication of an overloaded system",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(scylla_storage_proxy_coordinator_write_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) or on() vector(0)) + (sum(rate(scylla_storage_proxy_coordinator_read_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) or on() vector(0))"
    }
   ]
  },
  { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 } },
  {
   "title": "Writes",
   "type": "timeseries",
   "description": "Write attempts - include all writes that reached the coordinator node, even if they will eventually fail",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) or on ([[by]]) $func(rate(scylla_storage_proxy_coordinator_write_latency_summary_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Write Latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "wlatencyp95{by=\"cluster\", cluster=\"$cluster\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}} 95%"
    },
    {
     "expr": "wlatencyp99{by=\"cluster\", cluster=\"$cluster\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}} 99%"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "description": "Read attempts - include all reads that reached the coordinator node, even if they will eventually fail",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) or on ([[by]]) $func(rate(scylla_storage_proxy_coordinator_read_latency_summary_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval]))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Read Latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rlatencyp95{by=\"cluster\", cluster=\"$cluster\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}} {{instance}} {{shard}} 95%"
    },
    {
     "expr": "rlatencyp99{by=\"cluster\", cluster=\"$cluster\",scheduling_group_name=~\"$sg\"}>0",
     "legendFormat": "{{scheduling_group_name}} 99%"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "dc" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Information for $dc</h1>"
  },
  {
   "title": "Load",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{instance=~\"[[node]]\",cluster=~\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"} )"
    }
   ]
  },
  {
   "title": "Average Disk Usage",
   "type": "timeseries",
   "description": "The average Disk usage per [[by]].\n\n The dashed line represent the total size.",
   "gridPos": { "h": 6, "w": 3, "x": 1, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "Avg(node_filesystem_size_bytes{mountpoint=\"$mount_point\", dc=~\"$dc\", instance=~\"$node\"}) by ([[by]])-avg(node_filesystem_avail_bytes{mountpoint=\"$mount_point\",  dc=~\"$dc\", instance=~\"$node\"}) by ([[by]])",
     "legendFormat": "Avg Usage {{instance}} {{shard}}"
    },
    {
     "expr": "avg(node_filesystem_size_bytes{mountpoint=\"$mount_point\", dc=~\"$dc\", instance=~\"$node\"}) by ([[by]])",
     "legendFormat": "Size {{instance}} {{shard}}"
    }
   ]
  },
  {
   "title": "Running Compactions",
   "type": "timeseries",
   "description": "Holds the number of currently active compactions.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "$func(scylla_compaction_manager_compactions{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Cache Hits/Misses",
   "type": "timeseries",
   "description": "The Hits and Misses",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_cache_row_hits{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Hit {{instance}} {{shard}}"
    },
    {
     "expr": "$func(rate(scylla_cache_row_misses{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Misses {{instance}} {{shard}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 17, "w": 10, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "0*scylla_scylladb_current_version{cluster=\"$cluster\", dc=~\"$dc\"} + on (instance) group_left() scylla_node_operation_mode{cluster=\"$cluster\", dc=~\"$dc\"}"
    },
    {
     "expr": "avg(scylla_reactor_utilization{cluster=~\"$cluster\", dc=~\"$dc\"} ) by (instance)"
    },
    {
     "expr": "sum(rate(scylla_reactor_aio_errors{cluster=~\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by (instance)"
    },
    {
     "expr": "sum(scylla_errors:nodes_total{cluster=~\"$cluster\", dc=~\"$dc\"}) by (instance) >bool 0"
    },
    {
     "expr": "(sum(scylla_cql:non_system_prepared1m{cluster=~\"$cluster\", dc=~\"$dc\"}) by (instance) >bool 1) + (sum(rate(scylla_cql_reverse_queries{cluster=~\"$cluster\", dc=~\"$dc\"}[$__rate_interval])) by(instance) >bool 1) + (sum(scylla_cql:non_paged_no_system1m{cluster=~\"$cluster\", dc=~\"$dc\"}) by (instance) >bool 1)"
    },
    {
     "dashversion": [
      ">5.1",
      ">2022.2"
     ],
     "expr": "sum(scylla_gossip_live{cluster=\"$cluster\"})by (instance)"
    },
    {
     "dashversion": [
      ">5.2",
      ">2023.1"
     ],
     "expr": "(min(scylla_streaming_finished_percentage{cluster=\"$cluster\", dc=~\"$dc\"}*100) by (instance) < 100) or on (instance)  0*sum(scylla_scylladb_current_version{cluster=\"$cluster\", dc=~\"$dc\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "description": "Write attempts - include all writes that reached the coordinator node, even if they will eventually fail",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]) or on([[by]]) $func(rate(scylla_storage_proxy_coordinator_write_latency_summary_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Writes {{instance}} {{shard}}"
    },
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval] offset 1d)) or on ([[by]]) $func(rate(scylla_storage_proxy_coordinator_write_latency_summary_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval] offset 1d))",
     "legendFormat": "1 Day Ago"
    },
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval] offset 1w)) or on ([[by]]) $func(rate(scylla_storage_proxy_coordinator_write_latency_summary_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval] offset 1w))",
     "legendFormat": "1 Week Ago"
    }
   ]
  },
  {
   "title": "Write Latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(wlatencyp95{by=\"[[by]]\", instance=~\"[[node]]|^$\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\",scheduling_group_name=~\"$sg\"}>0) by (scheduling_group_name, [[by]])",
     "legendFormat": "{{scheduling_group_name}} 95% {{instance}} {{shard}}"
    },
    {
     "expr": "avg(wlatencyp99{by=\"[[by]]\", instance=~\"[[node]]|^$\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\",scheduling_group_name=~\"$sg\"}>0) by (scheduling_group_name, [[by]])",
     "legendFormat": "{{scheduling_group_name}} 99% {{instance}} {{shard}}"
    }
   ]
  },
  {
   "title": "Write Timeouts by [[by]]",
   "type": "timeseries",
   "description": "Requests that Scylla tried to write but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Writes {{instance}} {{shard}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "description": "Read attempts - include all reads that reached the coordinator node, even if they will eventually fail",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\",scheduling_group_name=~\"$sg\"}[$__rate_interval])) by ([[by]]) or on([[by]]) $func(rate(scylla_storage_proxy_coordinator_read_latency_summary_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\",scheduling_group_name=~\"$sg\"}[$__rate_interval])) by ([[by]])",
     "legendFormat": "Reads {{instance}} {{shard}}"
    },
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\",scheduling_group_name=~\"$sg\"}[$__rate_interval] offset 1d)) or on ([[by]]) $func(rate(scylla_storage_proxy_coordinator_read_latency_summary_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\",scheduling_group_name=~\"$sg\"}[$__rate_interval] offset 1d))",
     "legendFormat": "1 Day Ago"
    },
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\",scheduling_group_name=~\"$sg\"}[$__rate_interval] offset 1w)) or on ([[by]]) $func(rate(scylla_storage_proxy_coordinator_read_latency_summary_count{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\",scheduling_group_name=~\"$sg\"}[$__rate_interval] offset 1w))",
     "legendFormat": "1 Week Ago"
    }
   ]
  },
  {
   "title": "Read Latencies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg(rlatencyp95{by=\"[[by]]\", instance=~\"[[node]]|^$\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\",scheduling_group_name=~\"$sg\"}>0) by(scheduling_group_name, [[by]])",
     "legendFormat": "{{scheduling_group_name}} 95% {{instance}} {{shard}}"
    },
    {
     "expr": "avg(rlatencyp99{by=\"[[by]]\", instance=~\"[[node]]|^$\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]|$^\",scheduling_group_name=~\"$sg\"}>0) by(scheduling_group_name, [[by]])",
     "legendFormat": "{{scheduling_group_name}} 99% {{instance}} {{shard}}"
    }
   ]
  },
  {
   "title": "Read Timeouts by [[by]]",
   "type": "timeseries",
   "description": "Requests that Scylla tried to read but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } },
   "targets": [
    {
     "expr": "($func(rate(scylla_storage_proxy_coordinator_read_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]) or vector(0))+on([[by]]) ($func(rate(scylla_storage_proxy_coordinator_cas_read_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]) or vector(0))+on([[by]]) ($func(rate(scylla_storage_proxy_coordinator_range_timeouts{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", shard=~\"[[shard]]\"}[$__rate_interval])) by ([[by]]) or vector(0))",
     "legendFormat": "Read {{instance}} {{shard}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 10, "x": 14, "y": 38 },
   "options": {
    "content": "<img src=\"https://repositories.scylladb.com/scylla/imgversion/$all_scyllas_versions/scylla\"></img>"
   }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 10, "x": 14, "y": 38 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  { "title": "Your panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 46 },
   "options": {
    "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Your Panels</h1>"
   }
  },
  {
   "title": "Your Graph here",
   "type": "timeseries",
   "description": "This graph panel was left empty on purpose for ad-hoc usage. Change it when needed. Pay attention that changes to the panel will not be saved.\n\nIf you do need a panel that can be saved, create a new dashboard, or edit the panel inside the json file",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } }
  },
  {
   "title": "Your Graph here",
   "type": "timeseries",
   "description": "This graph panel was left empty on purpose for ad-hoc usage. Change it when needed. Pay attention that changes to the panel will not be saved.\n\nIf you do need a panel that can be saved, create a new dashboard, or edit the panel inside the json file",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "si:ops/s" } }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 54 },
   "options": {
    "content": "<div style=\"color:#5780C1; border-bottom: 0px solid #5780C1;\">Scylla Monitoring version - 4.8.3</div> <div style=\"\"><a href=\"https://github.com/scylladb/scylla-monitoring/issues/new?body=scylla-version%3D[[scylla_version]]%0Amonitoring-version%3D[[monitoring_version]]%0Adashboard%3D${__dashboard.uid}\" target=\"_blank\">\n<input title=\"Report an issue with Scylla Monitoring\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;Report an issue on this page&nbsp;\"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"/render/d/${__dashboard.uid}?orgId=1&from=${__from}&to=${__to}&width=1600&height=-1&kiosk\" target=\"_blank\" download=\"dashboard_${__dashboard.uid}-${__from:date:iso}.png\"><input title=\"Make a Screenshot\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;&nbsp;&nbsp;Screenshot&nbsp;&nbsp;&nbsp;\"></input></a></span></div>"
   }
  }
 ]
}