#!/bin/bash
#
# Copyright (C) 2025 ScyllaDB
#

set -euExo pipefail
shopt -s inherit_errexit

SO_SCYLLA_OPERATOR_REPLICAS="${SO_SCYLLA_OPERATOR_REPLICAS:-1}"
export SO_SCYLLA_OPERATOR_REPLICAS
SO_SCYLLA_OPERATOR_RESOURCE_REQUESTS_CPU="${SO_SCYLLA_OPERATOR_RESOURCE_REQUEST_CPU:-4}"
export SO_SCYLLA_OPERATOR_RESOURCE_REQUESTS_CPU
SO_SCYLLA_OPERATOR_RESOURCE_REQUESTS_MEMORY="${SO_SCYLLA_OPERATOR_RESOURCE_REQUESTS_MEMORY:-2Gi}"
export SO_SCYLLA_OPERATOR_RESOURCE_REQUESTS_MEMORY
SO_SCYLLA_OPERATOR_RESOURCE_LIMITS_CPU="${SO_SCYLLA_OPERATOR_RESOURCE_REQUEST_CPU:-4}"
export SO_SCYLLA_OPERATOR_RESOURCE_LIMITS_CPU
SO_SCYLLA_OPERATOR_RESOURCE_LIMITS_MEMORY="${SO_SCYLLA_OPERATOR_RESOURCE_LIMITS_MEMORY:-2Gi}"
export SO_SCYLLA_OPERATOR_RESOURCE_LIMITS_MEMORY

SCYLLA_OPERATOR_FEATURE_GATES="${SCYLLA_OPERATOR_FEATURE_GATES:-AllAlpha=true,AllBeta=true}"
export SCYLLA_OPERATOR_FEATURE_GATES
